import { municipalityNotes, servicePoint, stopCopy } from '../helpers'
import type { StopContent } from '../types'

export const bodrumCenter = {
  id: 'bodrum-center',
  routeId: 'izmir-to-lara',
  order: 9,
  slug: 'bodrum-center',
  ...stopCopy('bodrumCenter'),
  coordinates: { latitude: 37.0361912, longitude: 27.4271321 },
  recommendedNights: 1,
  minNights: 0,
  maxNights: 1,
  drivingDistanceFromPreviousKm: 23,
  estimatedDriveTimeMinutes: 35,
  seaScore: 3,
  silenceScore: 1,
  internetScore: 5,
  safetyScore: 4,
  solarSuitability: 'medium',
  shade: 'low',
  crowdLevel: 'high',
  ducatoAccessibility: 'caution',
  ducatoAccess: 'caution',
  droneSuitability: 'difficult',
  roadSurface: 'asphalt',
  roadWidth: 'busy urban streets near the old town and harbour',
  steepGrade: false,
  hairpins: false,
  cliffExposure: false,
  guardrails: true,
  turnaroundPossible: false,
  lastMileNote: 'content.stops.bodrumCenter.ops.lastMile',
  supplyNote: 'content.stops.bodrumCenter.ops.supply',
  decisionSummary: 'content.stops.bodrumCenter.ops.decision',
  municipalityFacilities: {
    available: true,
    wc: true,
    shower: false,
    potableWater: false,
    wasteBins: true,
    notes: municipalityNotes('bodrumCenter')
  },
  nearbyMarket: servicePoint('bodrumCenter', 'market', true, 1),
  fuelStation: servicePoint('bodrumCenter', 'fuel', true, 4),
  waterRefill: servicePoint('bodrumCenter', 'water', false, 0),
  dumpStation: servicePoint('bodrumCenter', 'dump', false, 0),
  freecampSpotIds: [],
  paidAlternativeIds: [],
  photos: [],
  initialStatus: 'planned',
  verificationStatus: 'partially_verified',
  sourceNote:
    'Bodrum Ferryboat identifies Bodrum Kale Port (Datca Ferry Pier) as the Bodrum departure point for the Datca service and asks passengers to arrive 30 minutes before departure. A legal Ducato overnight location in central Bodrum is not asserted.',
  lastVerifiedAt: '2026-07-30T00:00:00+03:00'
} satisfies StopContent
