import { municipalityNotes, servicePoint, stopCopy } from '../helpers'
import type { StopContent } from '../types'

export const cesmePalmiye = {
  id: 'cesme-palmiye',
  routeId: 'izmir-to-lara',
  order: 4,
  slug: 'cesme-palmiye',
  ...stopCopy('cesmePalmiye'),
  coordinates: { latitude: 38.3627304, longitude: 26.3163465 },
  recommendedNights: 1,
  minNights: 1,
  maxNights: 1,
  drivingDistanceFromPreviousKm: 95,
  estimatedDriveTimeMinutes: 80,
  seaScore: 4,
  silenceScore: 2,
  internetScore: 4,
  safetyScore: 3,
  solarSuitability: 'excellent',
  shade: 'low',
  crowdLevel: 'high',
  ducatoAccessibility: 'caution',
  ducatoAccess: 'caution',
  droneSuitability: 'difficult',
  roadSurface: 'asphalt',
  roadWidth: 'urban street',
  steepGrade: false,
  hairpins: false,
  cliffExposure: false,
  guardrails: true,
  turnaroundPossible: true,
  lastMileNote: 'content.stops.cesmePalmiye.ops.lastMile',
  supplyNote: 'content.stops.cesmePalmiye.ops.supply',
  decisionSummary: 'content.stops.cesmePalmiye.ops.decision',
  municipalityFacilities: {
    available: true,
    wc: true,
    shower: true,
    potableWater: false,
    wasteBins: true,
    notes: municipalityNotes('cesmePalmiye')
  },
  nearbyMarket: servicePoint('cesmePalmiye', 'market', true, 2),
  fuelStation: servicePoint('cesmePalmiye', 'fuel', true, 5),
  waterRefill: servicePoint('cesmePalmiye', 'water', false, 0),
  dumpStation: servicePoint('cesmePalmiye', 'dump', false, 0),
  freecampSpotIds: [],
  paidAlternativeIds: [],
  photos: [],
  initialStatus: 'planned',
  verificationStatus: 'partially_verified',
  sourceNote:
    'Palmiye Beach address cross-checked with public map and travel listings; operating conditions and overnight permission require an arrival check.',
  lastVerifiedAt: '2026-07-30T00:00:00+03:00'
} satisfies StopContent
