import { municipalityNotes, servicePoint, stopCopy } from '../helpers'
import type { StopContent } from '../types'

export const gerisPiknik = {
  id: 'geris-piknik',
  routeId: 'izmir-to-lara',
  order: 8,
  slug: 'geris-piknik',
  ...stopCopy('gerisPiknik'),
  coordinates: { latitude: 37.0796, longitude: 27.2771 },
  recommendedNights: 1,
  minNights: 0,
  maxNights: 1,
  drivingDistanceFromPreviousKm: 10,
  estimatedDriveTimeMinutes: 17,
  seaScore: 3,
  silenceScore: 4,
  internetScore: null,
  safetyScore: 3,
  solarSuitability: 'medium',
  shade: 'medium',
  crowdLevel: 'medium',
  ducatoAccessibility: 'caution',
  ducatoAccess: 'caution',
  droneSuitability: 'caution',
  roadSurface: 'mixed',
  roadWidth: 'local access road',
  steepGrade: null,
  hairpins: null,
  cliffExposure: null,
  guardrails: null,
  turnaroundPossible: null,
  lastMileNote: 'content.stops.gerisPiknik.ops.lastMile',
  supplyNote: 'content.stops.gerisPiknik.ops.supply',
  decisionSummary: 'content.stops.gerisPiknik.ops.decision',
  municipalityFacilities: {
    available: false,
    wc: false,
    shower: false,
    potableWater: false,
    wasteBins: false,
    notes: municipalityNotes('gerisPiknik')
  },
  nearbyMarket: servicePoint('gerisPiknik', 'market', false, 0),
  fuelStation: servicePoint('gerisPiknik', 'fuel', false, 0),
  waterRefill: servicePoint('gerisPiknik', 'water', false, 0),
  dumpStation: servicePoint('gerisPiknik', 'dump', false, 0),
  freecampSpotIds: ['geris-piknik-freecamp'],
  paidAlternativeIds: [],
  photos: [],
  initialStatus: 'planned',
  verificationStatus: 'partially_verified',
  sourceNote:
    'Community listings describe Geriş as a small sea-view camping or picnic area with capacity around 20 vehicles. Current access, signs and overnight rules must be checked on arrival; no services are guaranteed.',
  lastVerifiedAt: '2026-07-30T00:00:00+03:00'
} satisfies StopContent
