import { municipalityNotes, servicePoint, stopCopy } from '../helpers'
import type { StopContent } from '../types'

export const ilginKoyu = {
  id: 'ilgin-koyu',
  routeId: 'izmir-to-lara',
  order: 10,
  slug: 'ilgin-koyu',
  ...stopCopy('ilginKoyu'),
  coordinates: { latitude: 37.0010509, longitude: 27.7560274 },
  recommendedNights: 1,
  minNights: 1,
  maxNights: 1,
  drivingDistanceFromPreviousKm: 5,
  estimatedDriveTimeMinutes: 12,
  seaScore: 5,
  silenceScore: 5,
  internetScore: 2,
  safetyScore: 3,
  solarSuitability: 'high',
  shade: 'medium',
  crowdLevel: 'low',
  ducatoAccessibility: 'caution',
  ducatoAccess: 'caution',
  droneSuitability: 'good',
  roadSurface: 'asphalt then variable coastal surface',
  roadWidth: 'narrow final approach',
  steepGrade: true,
  hairpins: true,
  cliffExposure: false,
  guardrails: false,
  turnaroundPossible: null,
  lastMileNote: 'content.stops.ilginKoyu.ops.lastMile',
  supplyNote: 'content.stops.ilginKoyu.ops.supply',
  decisionSummary: 'content.stops.ilginKoyu.ops.decision',
  municipalityFacilities: {
    available: false,
    wc: false,
    shower: false,
    potableWater: false,
    wasteBins: false,
    notes: municipalityNotes('ilginKoyu')
  },
  nearbyMarket: servicePoint('ilginKoyu', 'market', true, 5),
  fuelStation: servicePoint('ilginKoyu', 'fuel', true, 28),
  waterRefill: servicePoint('ilginKoyu', 'water', false, 0),
  dumpStation: servicePoint('ilginKoyu', 'dump', false, 0),
  freecampSpotIds: ['ilgin-koyu-wildcamp'],
  paidAlternativeIds: [],
  photos: [],
  initialStatus: 'planned',
  verificationStatus: 'partially_verified',
  sourceNote:
    'The destination and coordinates were supplied by the travellers. Public travel records support Ilgın as a natural camping candidate, but not as a licensed campsite or guaranteed overnight permission.',
  lastVerifiedAt: '2026-07-30T00:00:00+03:00'
} satisfies StopContent
