import { municipalityNotes, servicePoint, stopCopy } from '../helpers'
import type { StopContent } from '../types'

export const izmirRestart = {
  id: 'izmir-restart',
  routeId: 'izmir-to-lara',
  order: 3,
  slug: 'izmir-restart',
  ...stopCopy('izmirRestart'),
  coordinates: { latitude: 38.4897894, longitude: 27.1649118 },
  recommendedNights: 1,
  minNights: 1,
  maxNights: 1,
  drivingDistanceFromPreviousKm: 180,
  estimatedDriveTimeMinutes: 150,
  seaScore: 3,
  silenceScore: 1,
  internetScore: 5,
  safetyScore: 4,
  solarSuitability: 'excellent',
  shade: 'low',
  crowdLevel: 'high',
  ducatoAccessibility: 'good',
  ducatoAccess: 'comfortable',
  droneSuitability: 'difficult',
  roadSurface: 'asphalt',
  roadWidth: 'urban main road',
  steepGrade: false,
  hairpins: false,
  cliffExposure: false,
  guardrails: true,
  turnaroundPossible: true,
  lastMileNote: 'content.stops.izmirRestart.ops.lastMile',
  supplyNote: 'content.stops.izmirRestart.ops.supply',
  decisionSummary: 'content.stops.izmirRestart.ops.decision',
  municipalityFacilities: {
    available: false,
    wc: false,
    shower: false,
    potableWater: false,
    wasteBins: true,
    notes: municipalityNotes('izmirRestart')
  },
  nearbyMarket: servicePoint('izmirRestart', 'market', true, 1),
  fuelStation: servicePoint('izmirRestart', 'fuel', true, 3),
  waterRefill: servicePoint('izmirRestart', 'water', false, 0),
  dumpStation: servicePoint('izmirRestart', 'dump', false, 0),
  freecampSpotIds: [],
  paidAlternativeIds: [],
  photos: [],
  initialStatus: 'current',
  verificationStatus: 'verified',
  sourceNote: 'Bayraklı TOKİ 7. Etap home return point after the completed Bafa Lake leg.',
  lastVerifiedAt: '2026-07-30T00:00:00+03:00'
} satisfies StopContent
