import { municipalityNotes, servicePoint, stopCopy } from '../helpers'
import type { StopContent } from '../types'

export const patara = {
  id: 'patara',
  routeId: 'izmir-to-lara',
  order: 14,
  slug: 'patara',
  ...stopCopy('patara'),
  coordinates: { latitude: 36.2704, longitude: 29.3034 },
  recommendedNights: 1,
  minNights: 1,
  maxNights: 1,
  drivingDistanceFromPreviousKm: 59,
  estimatedDriveTimeMinutes: 112,
  seaScore: 5,
  silenceScore: 4,
  internetScore: 4,
  safetyScore: 3,
  solarSuitability: 'excellent',
  shade: 'medium',
  crowdLevel: 'medium',
  ducatoAccessibility: 'caution',
  ducatoAccess: 'caution',
  droneSuitability: 'difficult',
  roadSurface: 'asphalt then rough track',
  roadWidth: 'narrow final approach',
  steepGrade: true,
  hairpins: true,
  cliffExposure: false,
  guardrails: false,
  turnaroundPossible: true,
  lastMileNote: 'content.stops.patara.ops.lastMile',
  supplyNote: 'content.stops.patara.ops.supply',
  decisionSummary: 'content.stops.patara.ops.decision',
  municipalityFacilities: {
    available: false,
    wc: false,
    shower: false,
    potableWater: false,
    wasteBins: true,
    notes: municipalityNotes('patara')
  },
  nearbyMarket: servicePoint('patara', 'market', true, 4),
  fuelStation: servicePoint('patara', 'fuel', true, 14),
  waterRefill: servicePoint('patara', 'water', false, 0),
  dumpStation: servicePoint('patara', 'dump', false, 0),
  freecampSpotIds: ['patara-dunes-wildcamp'],
  paidAlternativeIds: [],
  photos: [],
  initialStatus: 'planned',
  verificationStatus: 'partially_verified',
  sourceNote:
    'Patara dune-overlook coordinates and recent motorhome access reports cross-checked with Park4Night and CamperOnLine. Patara is a protected turtle-nesting coast; overnight parking remains an arrival-check decision, not a guaranteed permission.',
  lastVerifiedAt: '2026-07-30T00:00:00+03:00'
} satisfies StopContent
