import { municipalityNotes, servicePoint, stopCopy } from '../helpers'
import type { StopContent } from '../types'

export const torba = {
  id: 'torba',
  routeId: 'izmir-to-lara',
  order: 5,
  slug: 'torba',
  ...stopCopy('torba'),
  coordinates: { latitude: 37.0682, longitude: 27.4597 },
  recommendedNights: 1,
  minNights: 1,
  maxNights: 1,
  drivingDistanceFromPreviousKm: 320,
  estimatedDriveTimeMinutes: 250,
  seaScore: 4,
  silenceScore: 2,
  internetScore: 4,
  safetyScore: 4,
  solarSuitability: 'excellent',
  shade: 'low',
  crowdLevel: 'high',
  ducatoAccessibility: 'good',
  ducatoAccess: 'comfortable',
  droneSuitability: 'difficult',
  roadSurface: 'asphalt',
  roadWidth: 'normal',
  steepGrade: false,
  hairpins: false,
  cliffExposure: false,
  guardrails: true,
  turnaroundPossible: true,
  lastMileNote: 'content.stops.torba.ops.lastMile',
  supplyNote: 'content.stops.torba.ops.supply',
  decisionSummary: 'content.stops.torba.ops.decision',
  municipalityFacilities: {
    available: true,
    wc: true,
    shower: true,
    potableWater: false,
    wasteBins: true,
    notes: municipalityNotes('torba')
  },
  nearbyMarket: servicePoint('torba', 'market', true, 2),
  fuelStation: servicePoint('torba', 'fuel', true, 4),
  waterRefill: servicePoint('torba', 'water', false, 0),
  dumpStation: servicePoint('torba', 'dump', false, 0),
  freecampSpotIds: [],
  paidAlternativeIds: [],
  photos: [],
  initialStatus: 'planned',
  verificationStatus: 'partially_verified',
  sourceNote:
    'Beach identity, address and listed visitor facilities are based on Bodrum Municipality and the official public-beach listing; current caravan overnight permission must be confirmed.',
  lastVerifiedAt: '2026-07-30T00:00:00+03:00'
} satisfies StopContent
