import { municipalityNotes, servicePoint, stopCopy } from '../helpers'
import type { StopContent } from '../types'

export const yalikavak = {
  id: 'yalikavak',
  routeId: 'izmir-to-lara',
  order: 6,
  slug: 'yalikavak',
  ...stopCopy('yalikavak'),
  coordinates: { latitude: 37.1057, longitude: 27.2849 },
  recommendedNights: 0,
  minNights: 0,
  maxNights: 1,
  drivingDistanceFromPreviousKm: 20,
  estimatedDriveTimeMinutes: 30,
  seaScore: 4,
  silenceScore: 2,
  internetScore: 5,
  safetyScore: 4,
  solarSuitability: 'medium',
  shade: 'medium',
  crowdLevel: 'high',
  ducatoAccessibility: 'caution',
  ducatoAccess: 'caution',
  droneSuitability: 'difficult',
  roadSurface: 'asphalt',
  roadWidth: 'urban streets and marina traffic',
  steepGrade: false,
  hairpins: false,
  cliffExposure: false,
  guardrails: true,
  turnaroundPossible: false,
  lastMileNote: 'content.stops.yalikavak.ops.lastMile',
  supplyNote: 'content.stops.yalikavak.ops.supply',
  decisionSummary: 'content.stops.yalikavak.ops.decision',
  municipalityFacilities: {
    available: true,
    wc: true,
    shower: false,
    potableWater: false,
    wasteBins: true,
    notes: municipalityNotes('yalikavak')
  },
  nearbyMarket: servicePoint('yalikavak', 'market', true, 1),
  fuelStation: servicePoint('yalikavak', 'fuel', true, 3),
  waterRefill: servicePoint('yalikavak', 'water', false, 0),
  dumpStation: servicePoint('yalikavak', 'dump', false, 0),
  freecampSpotIds: [],
  paidAlternativeIds: [],
  photos: [],
  initialStatus: 'planned',
  verificationStatus: 'partially_verified',
  sourceNote:
    'Yalıkavak is used as a flexible daytime logistics and dinner waypoint between Torba and Gümüşlük. No specific Hepsiburada pickup point is hardcoded because pickup locations must be selected and checked in the delivery app at the time of ordering.',
  lastVerifiedAt: '2026-07-30T00:00:00+03:00'
} satisfies StopContent
