export default {
  placeholder: {
    routeTitle: 'İzmir to Lara', routeDescription: 'Personal caravan route.', region: 'Location details pending', overview: 'Content will be added after the location is verified.',
    whyVisit: 'Visit notes have not been added yet.', sunrise: 'Sunrise location not added.', sunset: 'Sunset location not added.'
  },
  route: {
    title: 'Aegean to Mediterranean Caravan Route',
    description: 'A slow coastal journey from İzmir to Antalya through quiet bays, ancient landscapes and pine-backed beaches.'
  },
  facilities: { electricity: 'Electricity', freshWater: 'Fresh water', wc: 'WC', shower: 'Shower', wasteDisposal: 'Waste disposal', restaurant: 'Restaurant', wasteBins: 'Waste bins nearby', shade: 'Shade', supermarkets: 'Supermarkets nearby' },
  prices: { permitted: 'Free where parking is permitted', permission: 'Free with local permission', seasonal: 'Seasonal rate; confirm directly', reserve: 'Seasonal rate; reservation recommended', premium: 'Premium seasonal rate; book ahead', local: 'Ask locally; rates vary' },
  stops: {
    izmir: {
      title: 'İzmir', region: 'Konak, İzmir', overview: 'A practical urban starting point around Konak and the Kordon, combining major-city provisioning with an easy waterfront walk before the coastal route begins.', whyVisit: 'Use the first day to stock the van, resolve vehicle errands and explore Kordon, Kemeraltı and the historic centre on foot. Treat it as a city base rather than a freecamp destination.',
      luna: { subject: 'Kordon ferries, promenade rhythm and blue-hour reflections', lens: '24 mm main camera or 70 mm telephoto for layered ferries', timing: 'Late golden hour through early blue hour', settings: 'RAW, slight negative exposure compensation, stabilize for blue hour', note: 'Work from public promenade space, keep moving cyclists and pedestrians clear, and avoid intrusive close portraits.' },
      municipality: 'General city services are available across Konak, but no dedicated municipal motorhome service point has been verified for this guide.', marketName: 'Konak and Alsancak supermarkets', marketNotes: 'Urban supermarkets and Kemeraltı food traders make this the strongest provisioning stop on the route; confirm vehicle-friendly parking before entering dense streets.', fuelName: 'Urban fuel stations', fuelNotes: 'Multiple city stations are expected, but select one on a main approach road and verify height and turning space.', waterName: 'Potable refill not verified', waterNotes: 'No dedicated public motorhome water point has been verified. Only fill from a clearly potable source with permission.', dumpName: 'Dump station not verified', dumpNotes: 'No licensed public dump point has been verified. Keep tanks closed until a confirmed service facility is available.', warning1: 'Konak and Alsancak are dense urban areas; use major roads, avoid narrow centre streets and check parking restrictions before committing a Ducato.', warning2: 'Do not interpret ordinary waterfront parking as permission to stay overnight; signs and enforcement can change.', sunrise: 'No specific sunrise location has been verified; scout an unobstructed public section of the inner-gulf waterfront in daylight.', sunset: 'The Kordon waterfront is the dependable evening subject: ferries, promenade activity and the western sky work well from public space.', photoAlt: 'İzmir Kordon waterfront during evening light'
    },
    guzelcamli: {
      title: 'Güzelçamlı', region: 'Kuşadası, Aydın', overview: 'A compact coastal town beside the entrance to Dilek Peninsula–Büyük Menderes Delta National Park, useful as a base for protected coves, walking and nature photography.', whyVisit: 'The national park brings beaches, coastal cliffs, maquis, forest and wetland habitats into one stop. Stay in the town or a confirmed campsite and visit the protected area within current access rules.',
      luna: { subject: 'Pine-framed coves, coastal textures and protected-habitat details', lens: '24 mm main camera; 70 mm for distant landscape layers', timing: 'Early or late daylight within published park access hours', settings: 'RAW, protect water highlights, use stabilization rather than leaving marked paths', note: 'Photograph from established roads, beaches and viewpoints. Give wildlife distance and never trade habitat protection for a frame.' },
      municipality: 'Town and seasonal visitor facilities may be available, but shower, toilet and motorhome-service details have not been independently verified for the intended travel date.', marketName: 'Güzelçamlı town supermarkets', marketNotes: 'Everyday food shopping is expected in the town centre; exact businesses, opening hours and Ducato parking should be checked on arrival.', fuelName: 'Fuel before the park', fuelNotes: 'No specific station is recorded in this guide. Confirm a suitable station on the Kuşadası–Söke approach before entering the peninsula.', waterName: 'Potable refill not verified', waterNotes: 'No public motorhome refill point has been verified. Arrange potable water through an authorised campsite or another confirmed source.', dumpName: 'Dump station not verified', dumpNotes: 'No public dump station has been verified. Use only a campsite or service point that explicitly accepts motorhome waste.', warning1: 'Dilek Peninsula is a protected national park. Check current opening hours, vehicle rules, fire restrictions and parking instructions on the official DKMP channel before entering.', warning2: 'Do not assume that daytime vehicle access or beach parking permits overnight stays or freecamping.', sunrise: 'No exact sunrise viewpoint is recorded; choose an authorised public shoreline or park viewpoint only after checking opening hours.', sunset: 'Use an established west-facing cove or town waterfront position and leave enough time to exit before any published closing time.', photoAlt: 'Protected Aegean cove on the Dilek Peninsula'
    },
    bafaLake: {
      title: 'Bafa Lake', region: 'Milas, Muğla', overview: 'A protected lake and archaeological landscape where Kapıkırı village sits among the remains of Herakleia, beneath the rock forms of Latmos.', whyVisit: 'Bafa rewards slow exploration: lakeshore atmosphere, ancient walls and the Athena temple can be experienced in the same landscape. It is a sensitive nature park, so access and overnight decisions should be conservative.',
      luna: { subject: 'Latmos rock forms, Herakleia masonry and restrained lake reflections', lens: '24 mm main camera for landscape; 70 mm for compressed rock and ruin details', timing: 'Soft dawn light or the final hour before sunset', settings: 'RAW, low ISO where stable, exposure bracket for bright sky and dark stone', note: 'Scout compositions in daylight, remain on established access, and do not seek or geotag sensitive rock-art locations without qualified local guidance.' },
      municipality: 'Kapıkırı is a small village within a protected archaeological and natural setting. No dedicated municipal motorhome service facility has been verified.', marketName: 'Full supermarket not verified near Kapıkırı', marketNotes: 'Do not rely on a full provisioning stop at the lake. Complete major shopping before leaving a larger town and support local businesses where available.', fuelName: 'Fuel on the main-road approach', fuelNotes: 'No specific Ducato-suitable station is recorded. Refuel on the main corridor before turning toward Kapıkırı.', waterName: 'Potable refill not verified', waterNotes: 'No verified public potable motorhome tap is recorded. Arrive self-sufficient and never draw water from the protected lake.', dumpName: 'Dump station not verified', dumpNotes: 'No verified disposal point is recorded. Carry all black and grey water to a licensed facility elsewhere.', warning1: 'The final village approach and parking geometry have not been independently checked for every Ducato length; inspect the route in daylight and do not block village access.', warning2: 'Stay off soft or vegetated shoreline ground and follow all nature-park and archaeological-site instructions.', sunrise: 'Kapıkırı’s established public lakeshore access can offer dawn light across water and rock forms; inspect safe, permitted footing the day before.', sunset: 'Look for evening side-light on the Herakleia stonework and Latmos formations from established public paths rather than climbing unmarked ruins.', photoAlt: 'Bafa Lake and Latmos rock landscape near Kapıkırı'
    },
    gumusluk: {
      title: 'Gümüşlük', region: 'Bodrum, Muğla', overview: 'A compact west-coast Bodrum settlement where the waterfront, small-boat activity and evening light create a slower counterpoint to the peninsula’s larger resort centres.', whyVisit: 'Use Gümüşlük for a waterfront walk and an unhurried evening. The official Muğla tourism calendar also records a Wednesday local market; confirm its current location and hours before setting out.',
      luna: { subject: 'Fishing boats and Rabbit Island', lens: '70 mm telephoto', timing: 'Sunset through blue hour', settings: 'RAW, -0.7 EV, stabilize the phone', note: 'Compress the boats against the island.' },
      municipality: 'No dedicated municipal motorhome service point has been verified.', marketName: 'Wednesday local market', marketNotes: 'The market day is listed by official Muğla tourism; current location, hours, vehicle access and nearby supermarket options need direct confirmation.', fuelName: 'Fuel stop not selected', fuelNotes: 'Choose a station on a main peninsula road after checking Ducato access.', waterName: 'Potable refill not verified', waterNotes: 'Do not rely on a public tap; obtain permission and confirm potability before filling.', dumpName: 'Dump station not verified', dumpNotes: 'Keep tanks closed until a licensed disposal point is confirmed.', warning1: 'Waterfront lane geometry and legal Ducato parking have not been field-verified; approach in daylight and follow signs.', warning2: 'Ordinary parking is not treated as overnight or camping permission.', sunrise: 'No exact sunrise position has been verified; scout a legal public viewpoint in daylight.', sunset: 'The west-facing public waterfront is the guide’s evening subject; confirm access and safe parking on arrival.', photoAlt: 'Gümüşlük waterfront in evening light'
    },
    akyarlar: {
      title: 'Akyarlar', region: 'Bodrum, Muğla', overview: 'A coastal stop at the southern end of the Bodrum Peninsula, associated in official tourism material with Akyarlar and Kefaluka Bay.', whyVisit: 'Pause for the open coastal setting and a slower beach day, subject to current beach access and weather. Official Muğla tourism also records a Thursday market.',
      luna: { subject: 'Kos silhouette and windsurfers', lens: '70 mm telephoto', timing: 'Late afternoon', settings: '1/1000 s, Auto ISO, burst mode', note: 'Protect the phone from salt spray in strong wind.' },
      municipality: 'Seasonal public-beach facilities and a motorhome service point have not been verified.', marketName: 'Thursday local market', marketNotes: 'The market day is officially listed; current location, hours and suitable Ducato parking must be checked locally.', fuelName: 'Fuel stop not selected', fuelNotes: 'Refuel at a confirmed main-road station before the next rural leg.', waterName: 'Potable refill not verified', waterNotes: 'Use only a confirmed potable source with permission.', dumpName: 'Dump station not verified', dumpNotes: 'Use only a facility that explicitly accepts motorhome waste.', warning1: 'Current beach parking rules and turning space for a long-wheelbase Ducato require an arrival-day check.', warning2: 'Check wind, signs and overnight restrictions rather than relying on an old parking report.', sunrise: 'No exact sunrise position has been verified; scout legal public shoreline access first.', sunset: 'Use an established public shoreline position only after checking access and wind conditions.', photoAlt: 'Akyarlar coastline and open Aegean view'
    },
    mazi: {
      title: 'Mazı', region: 'Bodrum, Muğla', overview: 'A rural coastal settlement on the less urbanised side of the Bodrum district, used here as a cautious gateway to the surrounding shoreline.', whyVisit: 'Choose Mazı for a quieter coastal rhythm and landscape photography, while treating each cove road, parking area and overnight option as something to verify locally.',
      luna: { subject: 'Pine ridges, coves and the Milky Way', lens: '24 mm main camera', timing: 'Blue hour or a moonless night', settings: 'Night mode on tripod; RAW by day', note: 'Use stable ground and switch headlights off during exposures.' },
      municipality: 'No municipal motorhome services have been verified.', marketName: 'Friday local market', marketNotes: 'Official Muğla tourism lists Friday as Mazı’s market day; current location, range and parking need confirmation.', fuelName: 'Fuel stop not selected', fuelNotes: 'Arrive with sufficient fuel; no specific station is endorsed.', waterName: 'Potable refill not verified', waterNotes: 'Arrive self-sufficient and confirm any source before filling.', dumpName: 'Dump station not verified', dumpNotes: 'Carry waste to a licensed service point.', warning1: 'Exact cove-road width, gradient and Ducato turning space have not been field-verified; inspect the chosen approach in daylight.', warning2: 'Check current forest-fire restrictions and never block forestry or emergency access.', sunrise: 'No exact dawn viewpoint is endorsed; use established public access after a daylight scout.', sunset: 'Select an established public viewpoint with firm parking, well away from road and emergency access.', photoAlt: 'Mazı coastal landscape below wooded slopes'
    },
    akbuk: {
      title: 'Akbük Bay', region: 'Gökova Gulf, Muğla', overview: 'A named stop on the Ören–Akbük–Gökova coastal itinerary documented in official Muğla tourism material.', whyVisit: 'Use the bay as a scenic break on the Gökova leg, but confirm the final road, beach access and overnight rules before committing a large van.',
      luna: { subject: 'Gökova water colours and mountain layers', lens: '24 mm main camera', timing: 'First hour after sunrise', settings: 'RAW, -0.3 EV, optional polarizer', note: 'Use established viewpoints before haze develops.' },
      municipality: 'No dedicated municipal motorhome service point has been verified.', marketName: 'Provisioning not verified in Akbük', marketNotes: 'Complete major shopping before the bay unless current local options are confirmed.', fuelName: 'Fuel stop not selected', fuelNotes: 'Refuel on a confirmed main-road approach before the coastal turn.', waterName: 'Potable refill not verified', waterNotes: 'Beach showers, if present, must not be assumed potable or suitable for tank filling.', dumpName: 'Dump station not verified', dumpNotes: 'Retain waste for a licensed facility.', warning1: 'The final Akbük approach has not been field-verified for every Ducato size; review the current route and arrive in daylight.', warning2: 'Use only legal, firm parking and keep emergency access completely clear.', sunrise: 'No exact sunrise position has been verified; scout established shoreline access first.', sunset: 'No exact sunset viewpoint is endorsed; use legal established access and leave before visibility deteriorates.', photoAlt: 'Akbük Bay on the Gökova coast'
    },
    dalyan: {
      title: 'Dalyan', region: 'Ortaca, Muğla', overview: 'A town within the Köyceğiz–Dalyan Special Environmental Protection Area, shaped by a lake, reed channels, wetlands and the protected İztuzu coast.', whyVisit: 'Explore the wetland landscape and cultural setting with authorised local access while keeping turtle habitat and protected-area rules central to every decision.',
      luna: { subject: 'Lycian tombs above the Dalyan River', lens: '70 mm telephoto', timing: 'Late afternoon', settings: 'RAW, -0.3 EV, 1/250 s from boats', note: 'Ask for a slow boat pass and protect nesting wildlife.' },
      municipality: 'No dedicated municipal motorhome service point has been verified.', marketName: 'Dalyan provisioning options', marketNotes: 'Select a current supermarket after confirming opening hours and Ducato-compatible parking.', fuelName: 'Fuel stop not selected', fuelNotes: 'Choose a confirmed main-road station rather than relying on the compact riverfront.', waterName: 'Potable refill not verified', waterNotes: 'Arrange a confirmed potable source before filling.', dumpName: 'Dump station not verified', dumpNotes: 'Confirm a licensed facility before arrival.', warning1: 'İztuzu is protected turtle habitat; follow all official access, lighting and conservation instructions.', warning2: 'Do not enter reed, wetland or beach habitat with the van; legal parking and boat access must be confirmed locally.', sunrise: 'No exact public sunrise viewpoint is endorsed; use authorised access that does not disturb protected habitat.', sunset: 'The established town riverfront offers an evening subject; respect boat traffic, private property and wildlife.', photoAlt: 'Protected reed channels in the Dalyan landscape'
    },
    karaotBeach: {
      title: 'Karaot Beach', region: 'Fethiye, Muğla', overview: 'A municipal public-beach stop on the Fethiye coast, approached here conservatively because the wider Fethiye–Göcek shoreline includes sensitive protected habitat.', whyVisit: 'Use Karaot for a simple shoreline pause and low-impact photography after confirming current access, facilities and conservation boundaries.',
      luna: { subject: 'Wetland birds and beach grasses', lens: '70 mm telephoto', timing: 'Sunrise', settings: '1/1000 s, Auto ISO, burst mode', note: 'Photograph wildlife from a distance.' },
      municipality: 'Karaot is documented as a municipal public beach; current toilets, showers, opening conditions and motorhome services have not been verified.', marketName: 'Nearby supermarket not selected', marketNotes: 'Complete provisioning on the main Fethiye corridor unless a current local option is confirmed.', fuelName: 'Fuel stop not selected', fuelNotes: 'Use a confirmed main-road station before the beach turn.', waterName: 'Potable refill not verified', waterNotes: 'Do not treat a beach shower as a potable tank-fill point.', dumpName: 'Dump station not verified', dumpNotes: 'Use only a licensed facility that accepts motorhome waste.', warning1: 'Ground condition, barriers and Ducato turning space require an arrival-day check, especially after rain.', warning2: 'Remain outside dunes, vegetation and any signed conservation area; daytime parking does not imply overnight permission.', sunrise: 'No exact sunrise position is endorsed; choose established public access without entering habitat.', sunset: 'Use the public shoreline only within current access rules and return to legal parking before dark.', photoAlt: 'Karaot public beach and open coastal landscape'
    },
    faralya: {
      title: 'Faralya', region: 'Fethiye, Muğla', overview: 'A mountain village high above Butterfly Valley and the Mediterranean.', whyVisit: 'Experience the route’s biggest cliffs, cool evenings and dramatic sunsets.',
      luna: { subject: 'Butterfly Valley and layered headlands', lens: '70 mm telephoto', timing: 'Final forty minutes before sunset', settings: 'RAW, -0.7 EV, focus lock', note: 'Remain well behind unfenced cliff edges.' },
      municipality: 'No municipal motorhome service point has been verified; village services are dispersed.', marketName: 'Provisioning not verified in Faralya', marketNotes: 'Complete major shopping before the mountain leg unless a current local option is confirmed.', fuelName: 'Fuel stop not selected', fuelNotes: 'Refuel before the coastal climb at a station checked for Ducato access.', waterName: 'Potable refill not verified', waterNotes: 'Confirm permission and potability with a registered host before filling.', dumpName: 'Dump station not verified', dumpNotes: 'Do not empty any tank without explicit facility approval.', warning1: 'The final coastal road and parking geometry require current Ducato-specific checking; arrive in daylight and do not block passing places.', warning2: 'Stay well back from cliff edges and ignore any navigation suggestion that leaves established vehicle roads.', sunrise: 'No exact public sunrise location has been verified; use a legal established terrace only.', sunset: 'View Butterfly Valley only from established public access and remain well behind exposed edges.', photoAlt: 'Faralya cliffs above the Mediterranean'
    },
    kas: {
      title: 'Kaş', region: 'Antalya Province', overview: 'A lively Mediterranean town of diving boats and Lycian history.', whyVisit: 'Enjoy exceptional water, food and the coastal road around Kaputaş.',
      luna: { subject: 'Harbour boats and Kastellorizo', lens: '70 mm telephoto', timing: 'Blue hour', settings: 'RAW, 1/125 s, -0.7 EV', note: 'Use public viewpoints and respect border-zone restrictions.' },
      municipality: 'Beach and harbour visitor facilities are not treated as motorhome service points.', marketName: 'Kaş provisioning options', marketNotes: 'Choose a current supermarket after checking legal parking and vehicle access.', fuelName: 'Fuel stop not selected', fuelNotes: 'Select a confirmed D400-area station with sufficient turning room.', waterName: 'Potable refill not verified', waterNotes: 'Arrange a verified potable supply with permission.', dumpName: 'Dump station not verified', dumpNotes: 'Confirm a licensed motorhome-waste facility before relying on it.', warning1: 'Old-town streets, shoulders and parking suitability have not been verified for a long Ducato; use signed main access and legal parking.', warning2: 'Check current drone, protected-area, maritime and border-security rules before any flight.', sunrise: 'No exact sunrise position is endorsed; scout an established public harbour or cultural-site viewpoint within access hours.', sunset: 'Use a legal public coastal viewpoint and respect protected-area and border-zone instructions.', photoAlt: 'Kaş harbour and Mediterranean coast at dusk'
    },
    cirali: {
      title: 'Çıralı', region: 'Kemer, Antalya', overview: 'A low-rise village behind a protected mountain-backed beach.', whyVisit: 'Swim, explore Olympos and walk to the eternal flames of Yanartaş.',
      luna: { subject: 'Olympos ruins, beach dawn and Yanartaş', lens: '24 mm main camera', timing: 'Sunrise or blue hour', settings: 'RAW by day; Night mode at Yanartaş', note: 'Use no artificial light on the nesting beach.' },
      municipality: 'Current public-beach facilities and dedicated motorhome servicing have not been verified.', marketName: 'Çıralı provisioning options', marketNotes: 'Confirm current businesses, hours and Ducato parking locally.', fuelName: 'Fuel stop not selected', fuelNotes: 'Refuel on the main-road approach at a station confirmed for the vehicle.', waterName: 'Potable refill not verified', waterNotes: 'A campsite supply must be confirmed potable and used only with permission.', dumpName: 'Dump station not verified', dumpNotes: 'Ask explicitly before emptying any tank.', warning1: 'Çıralı and Olympos include protected habitat and turtle-nesting context; follow current beach access and lighting instructions.', warning2: 'The access road and garden entrances have not been verified for every Ducato length; descend in daylight and follow current signs.', sunrise: 'The established public beach can provide dawn light, subject to all nesting-season and access rules.', sunset: 'Use established access near the Olympos end without entering ruins outside opening conditions or disturbing habitat.', photoAlt: 'Çıralı beach beneath wooded mountains'
    },
    lara: {
      title: 'Lara', region: 'Muratpaşa, Antalya', overview: 'A broad public-beach area on Antalya’s eastern urban coast, with city logistics nearby and official visitor facilities at the beach.', whyVisit: 'Finish the route with an accessible city-coast stop and final provisioning; treat motorhome water, waste and overnight needs as separate services that still require confirmation.',
      luna: { subject: 'Beach, dune grasses and Beydağları', lens: '24 mm main camera', timing: 'First light', settings: 'RAW, -0.3 EV, level verticals', note: 'Stay outside fenced dunes and never fly near the airport.' },
      municipality: 'Official tourism information describes public-beach visitor facilities, including changing cabins and food service; no dedicated municipal motorhome service point is verified.', marketName: 'Lara urban provisioning', marketNotes: 'Select a current supermarket with legal Ducato parking rather than entering constrained local streets.', fuelName: 'Fuel stop not selected', fuelNotes: 'Choose a confirmed station on a main urban approach.', waterName: 'Potable refill not verified', waterNotes: 'No public motorhome tank-fill point is endorsed.', dumpName: 'Dump station not verified', dumpNotes: 'Confirm licensed disposal before ending or storing the vehicle.', warning1: 'Allow for current city, airport-road and hotel-transfer traffic; use live navigation for the final approach.', warning2: 'Check height barriers, parking restrictions and aviation/drone rules on arrival.', sunrise: 'The public beach is the natural dawn subject; choose an open authorised section after checking access.', sunset: 'For evening photography, use public shoreline space and confirm parking hours before leaving the van.', photoAlt: 'Lara public beach in soft Mediterranean light'
    }
  },
  guide: {
    izmir: {
      hiddenTitle: 'Kemeraltı and the historic centre', hiddenDescription: 'Walk from Konak Square into Kemeraltı, then choose the Agora or Historical Elevator according to time and opening conditions.',
      beachTitle: 'Urban waterfront, not a beach stop', beachDescription: 'Kordon is designed for walking, cycling and waterfront views. Use only officially designated swimming areas elsewhere and check current water and access information.',
      hikingTitle: 'Kordon–Konak urban walk', hikingDescription: 'Use the continuous public waterfront and central pedestrian streets for an easy city walk; this is an urban route, not a backcountry trail.',
      viewpointTitle: 'Historical Elevator terrace', viewpointDescription: 'The upper terrace of the Historical Elevator is an established city panorama over İzmir Bay; check current access before visiting.',
      seasonTitle: 'Flexible year-round city stop', seasonDescription: 'Plan around the current weather rather than a fixed season. Mild, dry conditions are preferable for the waterfront and historic-centre walk.',
      wcNotes: 'No dedicated public motorhome toilet facility has been verified for this guide.', showerNotes: 'No dedicated municipal motorhome shower has been verified for this guide.', electricityNotes: 'No public motorhome electricity connection has been verified for this guide.',
      practicalTitle: 'Urban driving plan', practicalDescription: 'Complete provisioning near a major approach road, park the Ducato in a legal space, and explore central Konak on foot or public transport.',
      freecampPrice: 'No endorsed freecamp location', photo1Alt: 'Kordon promenade and İzmir Bay', photo2Alt: 'Ferries crossing İzmir Bay at blue hour', photo3Alt: 'Historic streets and city lights in Konak'
    },
    guzelcamli: {
      hiddenTitle: 'The peninsula–delta contrast', hiddenDescription: 'The protected area combines a mountainous peninsula with delta and wetland habitats. Observe the transition only from authorised roads, paths and viewpoints.',
      beachTitle: 'Dilek Peninsula coves', beachDescription: 'İçmeler, Aydınlık, Kavaklıburun and Karasu are established cove names associated with the park; confirm which areas are open and accessible on the day.',
      hikingTitle: 'Dilek Peninsula nature routes', hikingDescription: 'Official tourism guidance identifies the peninsula for nature walking. Use only open, marked routes and confirm current park, fire and access restrictions first.',
      viewpointTitle: 'Authorised peninsula viewpoints', viewpointDescription: 'Look for coastal and delta views from established roads, paths and signed viewpoints; do not enter closed habitat or leave marked access.',
      seasonTitle: 'Walking outside peak heat', seasonDescription: 'Spring and autumn generally suit walking, while summer is oriented more toward swimming and can be busy. Always defer to current weather and park rules.',
      wcNotes: 'Public toilet availability and seasonal opening within the town or park have not been verified for the travel date.', showerNotes: 'No shower suitable for general motorhome use has been verified; beach facilities must not be assumed to be service points.', electricityNotes: 'No public motorhome electricity connection has been verified; arrange power only through a confirmed campsite.',
      practicalTitle: 'Check the park before departure', practicalDescription: 'Consult the official DKMP listing for current hours and restrictions, carry out everything you bring in, and return to a confirmed overnight location outside restricted areas.',
      freecampPrice: 'No endorsed freecamp location', photo1Alt: 'Pine-framed cove on the Dilek Peninsula', photo2Alt: 'Rocky Aegean shoreline and clear water near Güzelçamlı', photo3Alt: 'Protected coastal habitat in Dilek Peninsula National Park'
    },
    bafaLake: {
      hiddenTitle: 'Athena temple and Herakleia stonework', hiddenDescription: 'Kapıkırı is interwoven with Herakleia. Explore visible remains from established village paths and avoid climbing, moving stones or entering sensitive areas.',
      beachTitle: 'Protected lakeshore', beachDescription: 'Treat Bafa as a nature-park lakeshore rather than a conventional beach destination. Use established public access and follow local guidance on swimming and shoreline use.',
      hikingTitle: 'Herakleia cultural walk', hikingDescription: 'Explore the visible remains around Kapıkırı from established village paths. For longer Latmos routes, use qualified local guidance and avoid sensitive rock-art locations.',
      viewpointTitle: 'Athena temple landscape', viewpointDescription: 'Established access around the Athena temple and village gives broad views across the lake and Latmos rock forms without climbing ruins.',
      seasonTitle: 'Choose mild walking weather', seasonDescription: 'The exposed archaeological landscape is best approached in mild, stable weather. Check heat, wind and rain before committing to a longer walk.',
      wcNotes: 'No dependable public toilet for motorhome travellers has been verified in Kapıkırı.', showerNotes: 'No public motorhome shower has been verified in the protected lake setting.', electricityNotes: 'No public motorhome electricity connection has been verified; arrive energy self-sufficient or book a confirmed host.',
      practicalTitle: 'Arrive self-sufficient', practicalDescription: 'Carry water, complete major shopping and refuel before the village turn. Visit in daylight so the final approach and a legal parking option can be assessed calmly.',
      freecampPrice: 'No endorsed freecamp location', photo1Alt: 'Bafa Lake below the Latmos rock formations', photo2Alt: 'Herakleia stone remains within Kapıkırı village', photo3Alt: 'Dawn light across Bafa Lake and granite boulders'
    }
  },
  spots: {
    izmirFree: { title: 'No verified İzmir freecamp', overview: 'This guide does not endorse an urban freecamp coordinate in İzmir. Use a legal, confirmed overnight facility rather than treating waterfront parking as a campsite.', access: 'Check vehicle dimensions, parking signs and overnight permission directly before arrival.' },
    izmirPaid: { title: 'İnciraltı Caravan Facility', overview: 'A serviced urban base with easy central access.', access: 'Confirm vehicle-length limits when booking.' },
    guzelcamliFree: { title: 'No verified Güzelçamlı freecamp', overview: 'No unrestricted overnight location is endorsed. The adjacent national park is protected and daytime access must not be interpreted as camping permission.', access: 'Use a confirmed campsite or legal overnight area and recheck current park and municipal rules.' },
    guzelcamliPaid: { title: 'Güzelçamlı Campground', overview: 'A shaded base for visiting Dilek Peninsula.', access: 'Straightforward village access for a Ducato.' },
    bafaFree: { title: 'No verified Bafa Lake freecamp', overview: 'No lakeside freecamp coordinate is endorsed. The stop lies within a protected natural and archaeological landscape.', access: 'Arrange permission or a confirmed facility; stay off shoreline vegetation and archaeological ground.' },
    bafaPaid: { title: 'Kapıkırı Guesthouse Camping', overview: 'A small hosted option with basic village facilities.', access: 'Confirm pitch dimensions before entering the village.' },
    gumuslukFree: { title: 'Gümüşlük Inland Stopover', overview: 'An inland candidate away from waterfront congestion.', access: 'Private land is common; obtain explicit permission.' },
    gumuslukPaid: { title: 'Gümüşlük Caravan Camp', overview: 'A serviced base within reach of the village.', access: 'Use the main approach, not waterfront shortcuts.' },
    akyarlarFree: { title: 'Akyarlar Inland Stopover', overview: 'A candidate inland from regulated beach parking.', access: 'Check signs and prepare for strong wind.' },
    akyarlarPaid: { title: 'Akyarlar Coastal Campground', overview: 'A practical camp near the swimming bay.', access: 'Confirm height and length limits.' },
    maziFree: { title: 'Mazı Upper-Road Terrace', overview: 'A remote candidate above the steep beach roads.', access: 'Keep forestry and emergency routes completely clear.' },
    maziPaid: { title: 'Mazı Family Campground', overview: 'A simple shaded camp close to the coves.', access: 'Call ahead for road and pitch advice.' },
    akbukFree: { title: 'Akbük Upper-Bay Stopover', overview: 'An elevated candidate away from the beach strip.', access: 'Use only an established firm pull-off.' },
    akbukPaid: { title: 'Akbük Bay Campground', overview: 'A managed option beside Gökova’s clear water.', access: 'Ask about the steep approach and turning space.' },
    dalyanFree: { title: 'Dalyan Rural Stopover', overview: 'A rural candidate away from reeds and protected beach.', access: 'Avoid irrigation tracks and soft agricultural ground.' },
    dalyanPaid: { title: 'Dalyan Riverside Campground', overview: 'A serviced base for Kaunos and boat trips.', access: 'Avoid the compact riverfront centre.' },
    karaotFree: { title: 'Karaot Beach-Edge Stopover', overview: 'Firm ground outside dunes and wetland habitat.', access: 'Never cross conservation barriers.' },
    karaotPaid: { title: 'Karaot Eco Campground', overview: 'A managed nature-focused alternative near the beach.', access: 'Confirm opening dates and van capacity.' },
    faralyaFree: { title: 'Faralya Upper-Village Stopover', overview: 'A mountain candidate away from cliff edges.', access: 'Do not block passing bays on the coast road.' },
    faralyaPaid: { title: 'Faralya View Terrace Camp', overview: 'A managed cliff-top base with safe viewpoints.', access: 'Confirm Ducato dimensions in advance.' },
    kasFree: { title: 'Kaş Inland Plateau Stopover', overview: 'A cooler candidate away from the congested coast.', access: 'Use established ground with landowner permission.' },
    kasPaid: { title: 'Kaş Peninsula Campground', overview: 'A scenic serviced base with sea access.', access: 'The peninsula road is busy and narrow.' },
    ciraliFree: { title: 'Çıralı Upper-Village Stopover', overview: 'A village-edge candidate away from the nesting beach.', access: 'Respect wildfire closures and private land.' },
    ciraliPaid: { title: 'Çıralı Garden Campground', overview: 'A shaded citrus-garden base near the beach.', access: 'Some garden entrances are narrow.' },
    laraFree: { title: 'Lara Inland Stopover', overview: 'A short urban-edge candidate away from airport-sensitive areas.', access: 'Check height barriers and parking enforcement.' },
    laraPaid: { title: 'Antalya East Caravan Facility', overview: 'A serviced final-night base for onward logistics.', access: 'Avoid hotel-transfer rush hours.' }
  }
}
