type EnglishContent = typeof import('./en').default
type TranslationShape<T> = { [Key in keyof T]: T[Key] extends string ? string : TranslationShape<T[Key]> }

const content = {
  placeholder: {
    routeTitle: 'İzmir - Lara', routeDescription: 'Kişisel karavan rotası.', region: 'Konum bilgileri bekleniyor', overview: 'Konum doğrulandıktan sonra içerik eklenecek.',
    whyVisit: 'Ziyaret notları henüz eklenmedi.', sunrise: 'Gün doğumu konumu eklenmedi.', sunset: 'Gün batımı konumu eklenmedi.'
  },
  route: {
    title: 'Ege’den Akdeniz’e Karavan Rotası',
    description: 'İzmir’den Antalya’ya sakin koylar, antik coğrafyalar ve çamlarla çevrili sahiller boyunca yavaş bir kıyı yolculuğu.'
  },
  facilities: { electricity: 'Elektrik', freshWater: 'Temiz su', wc: 'WC', shower: 'Duş', wasteDisposal: 'Atık boşaltma', restaurant: 'Restoran', wasteBins: 'Yakında çöp kutusu', shade: 'Gölge', supermarkets: 'Yakında süpermarket' },
  prices: { permitted: 'Park izni olan yerlerde ücretsiz', permission: 'Yerel izinle ücretsiz', seasonal: 'Sezonluk ücret; doğrudan teyit edin', reserve: 'Sezonluk ücret; rezervasyon önerilir', premium: 'Yüksek sezon ücreti; önceden ayırtın', local: 'Yerinde sorun; ücretler değişebilir' },
  stops: {
    izmir: {
      title: 'İzmir', region: 'İzmir', overview: 'Kordon kıyısını merkez alan, şehir hizmetlerine ulaşılabilen kentsel rota başlangıcı.', whyVisit: 'Güneye inmeden önce aracı hazırlamak ve Kordon’da yürümek için şehir durağını kullanın. Gece parkı ve servis erişimini yerinde doğrulayın.',
      luna: { subject: 'Kordon vapurları ve sahil yansımaları', lens: '24 mm ana kamera', timing: 'Gün batımından yirmi dakika sonra', settings: 'RAW, -0,7 EV, en az 1/60 sn', note: 'Sahil ışıklarını kullanın; tanınabilir yakın portrelerden kaçının.' },
      municipality: 'Umumi tuvalet ve kutular yaygındır; karavan servisi bulunmaz.', marketName: 'Konak süpermarketleri', marketNotes: 'Büyük marketler ve yerel gıda pazarları.', fuelName: 'Şehir içi akaryakıt istasyonları', fuelNotes: 'D550 güneye çıkmadan depoyu doldurun.', waterName: 'Doğrulanmış halka açık karavan musluğu yok', waterNotes: 'Dolumdan önce kamp veya istasyondan izin alın.', dumpName: 'Doğrulanmış belediye boşaltım noktası yok', dumpNotes: 'Atığı lisanslı bir kampa kadar tutun.', warning1: 'Merkez trafiği işe gidiş saatlerinde yoğundur.', warning2: 'Yükseklik bariyerlerini ve geceleme levhalarını kontrol edin.', sunrise: 'İç körfeze doğuya bakan İnciraltı kıyısı.', sunset: 'Batı ufkundaki vapurlarla Kordon.', photoAlt: 'Sıcak akşam ışığında İzmir sahili'
    },
    guzelcamli: {
      title: 'Güzelçamlı', region: 'Kuşadası, Aydın', overview: 'Kara, deniz ve sulak alan habitatları korunan Dilek Yarımadası–Büyük Menderes Deltası Millî Parkı yanındaki kıyı üssü.', whyVisit: 'Güzelçamlı’yı doğa yürüyüşü ve fotoğraf için üs olarak kullanın. Güncel park saatlerini, araç erişimini ve geceleme kurallarını gelmeden kontrol edin.',
      spots: { hayalBahcesi: { title: 'Kuşadası Hayal Bahçesi Karavan Alanı', overview: 'Milli Park Caddesi’nde, plaja yaklaşık 50 metre ve millî park girişine 700 metre mesafedeki işletmeli karavan alanı. İşletme su, elektrik, sıcak duş ve ortak mutfak hizmetlerini listeliyor.', price: 'Sezon ücreti ve kapasite değişebilir; gelmeden arayın.', access: 'Milli Park Caddesi’ni ve 34 numaradaki işaretli girişi kullanın. Kasaba yaklaşımı asfalt ve Ducato için uygundur; kapıya gitmeden yer ayırtın.', safety: 'Yasal geceleme üssü burasıdır. Millî park otoparkları gündüz ziyareti içindir ve kampın uzantısı değildir.' } },
      luna: { subject: 'Çamlarla çevrili koylar ve berrak Ege', lens: '24 mm ana kamera', timing: 'Sabah erken saatler', settings: 'RAW, -0,3 EV, isteğe bağlı polarize filtre', note: 'Belirlenmiş patikalarda kalın ve yaban hayatını koruyun.' },
      municipality: 'Millî park koylarında çalışma saatleri içinde işaretli otoparklar ve ziyaretçi WC’leri bulunur; bunlar karavan servis noktası değildir.', marketName: 'Güzelçamlı marketleri', marketNotes: 'Meşelikuyu Caddesi’ndeki güncel Şok şubesi ve yerel pazar, parka girmeden temel alışverişi karşılar.', fuelName: 'Shell Davutlar Çıkışı', fuelNotes: 'Shell’in resmî kaydı; dizel, market, WC ve geçiş trafiğine uygun pompa alanı bulunan 24 saat açık istasyonu doğruluyor.', waterName: 'Hayal Bahçesi kamp suyu', waterNotes: 'Kamp işletmesi karavan misafirleri için su listeliyor. İçme tankına doldurmadan içilebilirliğini sorun.', dumpName: 'Kaset veya gri su boşaltımı doğrulanmadı', dumpNotes: 'Hayal Bahçesi boşaltım noktası ilan etmiyor; açıkça kabul eden bir tesis bulunana kadar tankları kapalı tutun.', warning1: 'Dilek Yarımadası içinde yalnızca işaretli otoparklara park edin ve ziyaretçi koylarında kalın. Millî park içinde kamp ve geceleme yapılamaz.', warning2: 'Araç girişi kapasiteyle sınırlandırılır ve yaz giriş saatleri değişebilir. Erken girin, ilan edilen son çıkıştan önce ayrılın.', sunrise: 'Park açılmadan önce kasaba kıyısını; kapı açıldıktan sonra ise yalnızca izinli koyları kullanın.', sunset: 'Güncel çıkış saati güvenli pay bırakmıyorsa park içinde gün batımı planlamayın; Güzelçamlı kıyısı daha düşük riskli alternatiftir.', photoAlt: 'Çamlarla çevrili turkuaz Ege koyu',
      ops: { lastMile: 'Güzelçamlı ve Milli Park Caddesi asfalt olup normal şartlarda Ducato için rahattır. Park içinde ana ziyaretçi yolundan ayrılmayın, yalnızca işaretli koy otoparklarını kullanın; kapasite dolunca kuyruk veya giriş durdurma bekleyin.', supply: 'Parka girmeden Güzelçamlı’da alışveriş yapın ve 24 saat açık Shell Davutlar Çıkışı’nda yakıt alın. Hayal Bahçesi karavan misafirlerine su sağlıyor; doldurmadan içilebilirliği teyit edin.', decision: 'Güzelçamlı’ya asfalt ana yoldan girin ve geceleme üssü olarak Hayal Bahçesi’ni kullanın. Dilek Yarımadası’nı yalnızca gündüz ziyaret edin, işaretli koy otoparklarına park edin ve kapanıştan önce çıkın. Millî park içindeki hiçbir cep veya plaj otoparkını freecamp saymayın. Korunan alana girmeden yiyecek, yakıt ve su işini bitirin.' }
    },
    bafaLake: {
      title: 'Bafa Gölü', region: 'Aydın–Muğla', overview: 'Latmos bölgesi ve Herakleia antik yerleşimiyle ilişkili korunan göl peyzajı.', whyVisit: 'Doğal ve kültürel peyzajı birlikte görmek için durun. Park, erişim ve koruma kurallarını konaklamadan önce yerinde doğrulayın.',
      spots: { selenes: { title: 'Selenes Pansiyon Bahçe Kampı', overview: 'Kapıkırı’daki işletmeli bahçe kampı. İşletme, korunan göl kıyısında ve Herakleia içinde kampın yasak olduğunu açıkça belirtiyor ve bahçesini yasal alternatif olarak sunuyor.', price: 'Güncel bahçe kampı ücretini sorun ve araç yeri ayırtın.', access: 'Asfalt Kapıkırı yolunu kullanın. Ana yoldan ayrılmadan 15 m³ Ducato ölçülerini bildirin; son köy sokakları ve bahçe manevrası karayolundan daha dardır.', safety: 'Yalnızca işletmenin gösterdiği alanda kalın. Yumuşak göl kıyısına veya arkeolojik zemine araçla girmeyin.' } },
      luna: { subject: 'Latmos yansımaları ve granit kayalar', lens: '24 mm ana kamera', timing: 'Gün doğumundan otuz dakika önce', settings: 'RAW, tripod, ISO 50, pozlama serisi', note: 'Dağlara ölçek vermek için önde bir kaya kullanın.' },
      municipality: 'Kapıkırı’da pansiyon ve restoranlar bulunur; belediyeye ait karavan servis istasyonu yoktur.', marketName: 'Büyük alışveriş Kapıkırı’dan önce', marketNotes: 'Kapıkırı’da küçük yerel işletmeler vardır ancak güvenilir bir tam süpermarket yoktur. Köy yoluna dönmeden Söke–Milas koridorunda ana alışverişi bitirin.', fuelName: 'Söke–Milas koridorunda yakıt', fuelNotes: 'Kapıkırı sapağına girmeden D525 üzerinde yakıt alın; köyde güvenilir bir akaryakıt istasyonu yoktur.', waterName: 'Teyit edilmiş işletmeden su', waterNotes: 'İçme suyu deposu dolu gelin. Selenes’ten misafir suyu sorulabilir; göl suyu hiçbir durumda ikmal kaynağı değildir.', dumpName: 'Kaset veya gri su boşaltımı yok', dumpNotes: 'Kapıkırı veya Selenes’te belgelenmiş boşaltım servisi yoktur; atığı lisanslı tesise geri taşıyın.', warning1: 'Asfalt Kapıkırı yaklaşımı köy binaları, taş duvarlar ve park etmiş araçlar arasında daralır. Gündüz varın ve Ducato ile dar yan sokakları keşfetmeyin.', warning2: 'Korunan göl kıyısı ve Herakleia arkeolojik zemini freecamp değildir. Kıyı zemini yağmurdan sonra yumuşayabilir.', sunrise: 'Kıyıya araçla girmeden, Kapıkırı’daki yerleşik erişimden şafak yansımalarını izleyin.', sunset: 'Herakleia taşlarını ve Latmos’u umumi köy patikalarından fotoğraflayın; kalıntılara veya yumuşak kıyıya çıkmayın.', photoAlt: 'Şafakta sarp dağların altındaki sakin göl',
      ops: { lastMile: 'Ana Kapıkırı yaklaşımı asfalttır; son köy kesiminde taş duvarlar, yapılar ve park etmiş araçlar nedeniyle yol yer yer dar, dönüş alanı sınırlıdır. İşaretli yaklaşımda kalın ve köye girmeden Selenes yerini ayarlayın.', supply: 'Ana gıda alışverişini ve yakıtı Söke–Milas D525 koridorunda tamamlayın. Kapıkırı’da güvenilir tam market, akaryakıt istasyonu ve karavan boşaltım noktası olmadığı için içme suyu dolu girin.', decision: 'Asfalt Kapıkırı yaklaşımını gündüz kullanın ve doğrudan Selenes gibi önceden ayarlanmış bir işletmeye gidin. Göl kıyısına araçla çıkmayın; korunan kıyı ve Herakleia’yı freecamp olarak kullanmayın. Köy sapağından önce D525 üzerinde su, yiyecek ve yakıtı tamamlayın. Gölü ve kalıntıları yerleşik köy erişiminden yürüyerek keşfedin.' }
    },
    gumusluk: {
      title: 'Gümüşlük', region: 'Bodrum, Muğla', overview: 'Antik Myndos çevresinde, batı manzaralı sakin kıyı yerleşimi.', whyVisit: 'Taş sokakları, kıyıyı ve Tavşan Adası gün batımını yaşayın.',
      spots: { mandi: { title: 'Mandi Camping', overview: 'Gümüşlük’e dört kilometre, denize kısa yürüyüş mesafesinde; temiz su, gri su gideri, elektrik ve kaset boşaltım terminalleri bulunan güvenlikli karavan kampı.', price: 'Rezervasyonu ve güncel sezon ücretini doğrudan teyit edin.', access: 'Sahil kestirmesi yerine işletmenin ana yol yaklaşımını kullanın. Son iniş dardır; 15 m³ Ducato için yer durumunu önceden sorun.' } },
      luna: { subject: 'Tavşan Adası ve kıyı katmanları', lens: '70 mm telefoto', timing: 'Gün batımından mavi saate', settings: 'RAW, -0,7 EV, telefonu sabitleyin', note: 'Ada ile kıyı katmanlarını sıkıştırın.' },
      municipality: 'Belediyeye ait karavan servis noktası doğrulanmadı.', marketName: 'Çarşamba yerel pazarı', marketNotes: 'Pazar günü Muğla’nın resmî turizm kaynağında yer alır; güncel konum, saat, araç erişimi ve market seçeneklerini doğrudan doğrulayın.', fuelName: 'Yakıt noktası seçilmedi', fuelNotes: 'Ducato erişimini kontrol ederek ana yarımada yollarındaki bir istasyonu seçin.', waterName: 'İçme suyu dolumu doğrulanmadı', waterNotes: 'Umumi musluğa güvenmeyin; izin alın ve içilebilirliği teyit edin.', dumpName: 'Boşaltım noktası doğrulanmadı', dumpNotes: 'Lisanslı tesis doğrulanana kadar tankları kapalı tutun.', warning1: 'Sahil sokakları ve yasal Ducato parkı sahada doğrulanmadı; gündüz yaklaşın ve levhalara uyun.', warning2: 'Normal park alanı geceleme veya kamp izni sayılmaz.', sunrise: 'Kesin bir gün doğumu noktası doğrulanmadı; gündüz yasal bir umumi seyir bulun.', sunset: 'Batıya bakan umumi sahil akşam konusudur; erişimi ve güvenli parkı varışta doğrulayın.', photoAlt: 'Akşam ışığında Gümüşlük sahili'
    },
    akyarlar: {
      title: 'Akyarlar', region: 'Bodrum, Muğla', overview: 'Sığ denizi ve Kos manzarasıyla güneye bakan koy.', whyVisit: 'Rahat bir yüzme günü geçirin, rüzgâr sörfçülerini fotoğraflayın.',
      spots: { cuce: { title: 'Cüce Camping Akyarlar', overview: 'İşletme politikasına bağlı olarak su, elektrik, duş ve WC hizmetleri bulunan Akyarlar’daki işletmeli karavan kampı.', price: 'Yer durumunu, sezon ücretini ve dahil hizmetleri yola çıkmadan teyit edin.', access: 'Ducato ölçülerini önceden bildirin ve işaretli ana yaklaşımı kullanın; serbest plaj parkına yönelmeyin.' } },
      luna: { subject: 'Kos silüeti ve rüzgâr sörfçüleri', lens: '70 mm telefoto', timing: 'Öğleden sonra', settings: '1/1000 sn, Otomatik ISO, seri çekim', note: 'Sert rüzgârda telefonu tuzlu sudan koruyun.' },
      municipality: 'Sezonluk plaj hizmetleri ve karavan servis noktası doğrulanmadı.', marketName: 'Perşembe yerel pazarı', marketNotes: 'Pazar günü resmî olarak listelenir; güncel konum, saat ve Ducato parkını yerinde kontrol edin.', fuelName: 'Yakıt noktası seçilmedi', fuelNotes: 'Sonraki kırsal etaptan önce ana yoldaki doğrulanmış bir istasyonda yakıt alın.', waterName: 'İçme suyu dolumu doğrulanmadı', waterNotes: 'Yalnızca izinli ve içilebilirliği teyit edilmiş kaynak kullanın.', dumpName: 'Boşaltım noktası doğrulanmadı', dumpNotes: 'Yalnızca karavan atığını açıkça kabul eden tesisi kullanın.', warning1: 'Plaj park kuralları ve uzun Ducato dönüş alanı seyahat gününde kontrol edilmelidir.', warning2: 'Eski park yorumlarına güvenmek yerine rüzgârı, levhaları ve geceleme kısıtlarını kontrol edin.', sunrise: 'Kesin gün doğumu noktası doğrulanmadı; önce yasal umumi kıyı erişimini inceleyin.', sunset: 'Rüzgâr ve erişim kontrolünden sonra yerleşik umumi kıyıyı kullanın.', photoAlt: 'Akyarlar kıyısı ve açık Ege manzarası'
    },
    mazi: {
      title: 'Mazı', region: 'Bodrum, Muğla', overview: 'Dik dağ yollarıyla ulaşılan çamlarla çevrili uzak koylar.', whyVisit: 'Tatil Bodrum’unun ötesinde berrak su, karanlık gökyüzü ve sessizlik bulun.',
      luna: { subject: 'Çam sırtları, koylar ve Samanyolu', lens: '24 mm ana kamera', timing: 'Mavi saat veya aysız gece', settings: 'Tripodda Gece modu; gündüz RAW', note: 'Sağlam zeminde durun, uzun pozlamada farları kapatın.' },
      municipality: 'Belediyeye ait karavan hizmeti doğrulanmadı.', marketName: 'Cuma yerel pazarı', marketNotes: 'Muğla’nın resmî turizm kaynağı Mazı pazarını cuma günü olarak listeler; konum, ürün ve parkı teyit edin.', fuelName: 'Yakıt noktası seçilmedi', fuelNotes: 'Yeterli yakıtla gelin; belirli bir istasyon önerilmiyor.', waterName: 'İçme suyu dolumu doğrulanmadı', waterNotes: 'Hazırlıklı gelin ve dolumdan önce kaynağı teyit edin.', dumpName: 'Boşaltım noktası doğrulanmadı', dumpNotes: 'Atığı lisanslı servis noktasına taşıyın.', warning1: 'Koy yollarının genişliği, eğimi ve Ducato dönüş alanı sahada doğrulanmadı; seçilen yaklaşımı gündüz inceleyin.', warning2: 'Güncel orman yangını kısıtlarını kontrol edin, orman ve acil geçişi kapatmayın.', sunrise: 'Kesin şafak noktası önerilmiyor; gündüz incelenmiş yerleşik umumi erişimi kullanın.', sunset: 'Sağlam parkı olan, yol ve acil geçişten uzak umumi bir seyir seçin.', photoAlt: 'Ormanlı yamaçlar altındaki Mazı kıyısı'
    },
    akbuk: {
      title: 'Akbük Koyu', region: 'Gökova Körfezi, Muğla', overview: 'Gökova tepeleriyle çevrili berrak sulu geniş koy.', whyVisit: 'İyi yüzme, açık körfez manzarası ve güçlü güneş verimini birleştirin.',
      spots: { pasali: { title: 'Paşalı Camping & Caravan', overview: 'Akbük kıyısına yakın, zeytin ağaçları altında ve kendi karavanıyla gelen misafirleri açıkça kabul eden küçük işletmeli karavan parkı.', price: 'Kapasite sınırlı olduğundan rezervasyon yapın ve güncel ücreti teyit edin.', access: 'Güvenlik bariyeri rezervasyon teyidi isteyebilir. Gündüz varın ve 15 m³ Ducato için dönüş alanını önceden sorun.' } },
      luna: { subject: 'Gökova su renkleri ve dağ katmanları', lens: '24 mm ana kamera', timing: 'Gün doğumundan sonraki ilk saat', settings: 'RAW, -0,3 EV, isteğe bağlı polarize filtre', note: 'Pus oluşmadan belirlenmiş seyirleri kullanın.' },
      municipality: 'Belediyeye ait karavan servis noktası doğrulanmadı.', marketName: 'Akbük’te ikmal doğrulanmadı', marketNotes: 'Güncel yerel seçenek doğrulanmadıkça büyük alışverişi koya gelmeden tamamlayın.', fuelName: 'Yakıt noktası seçilmedi', fuelNotes: 'Kıyı dönüşünden önce ana yoldaki doğrulanmış bir istasyonda yakıt alın.', waterName: 'İçme suyu dolumu doğrulanmadı', waterNotes: 'Varsa plaj duşlarını içilebilir veya depo dolumuna uygun kabul etmeyin.', dumpName: 'Boşaltım noktası doğrulanmadı', dumpNotes: 'Atığı lisanslı tesise taşıyın.', warning1: 'Son Akbük yaklaşımı her Ducato boyu için sahada doğrulanmadı; güncel rotayı inceleyip gündüz varın.', warning2: 'Yalnızca yasal ve sağlam park kullanın; acil geçişi tamamen açık tutun.', sunrise: 'Kesin bir gün doğumu noktası doğrulanmadı; önce yerleşik kıyı erişimini inceleyin.', sunset: 'Kesin bir seyir önerilmiyor; yasal erişim kullanın ve görüş azalmadan ayrılın.', photoAlt: 'Gökova kıyısındaki Akbük Koyu'
    },
    dalyan: {
      title: 'Dalyan', region: 'Ortaca, Muğla', overview: 'Likya mezarlarına ve korunan sazlıklara bakan nehir kasabası.', whyVisit: 'Ducato’yu doğrulanmış Sarıgerme karavan alanına bırakın. İsterseniz Dalyan merkezini ayrıca ziyaret edip izinli bir günübirlik geziye katılın; tekne yolculuğu sürüş rotasının parçası değildir.',
      spots: { sarigerme: { title: 'Sarıgerme Belediye Karavan Alanı', overview: 'Dalyan etabının pratik geceleme üssü olarak seçilen, Sarıgerme kıyısındaki belediye işletmeli çadır ve karavan alanı.', price: 'Güncel sezon ücreti Ortaca Belediyesi ile doğrudan teyit edilmelidir.', access: 'İşaretli Sarıgerme plajı yaklaşımını kullanın. Yola çıkmadan sezon açılışını ve Ducato için yer durumunu teyit edin.' } },
      luna: { subject: 'Dalyan Nehri üzerindeki Likya mezarları', lens: '70 mm telefoto', timing: 'Öğleden sonra', settings: 'RAW, -0,3 EV, izinli umumi seyirden sabitleyin', note: 'Ducato’yu yasal alanda bırakın. Tekne gezisi karavan rotası değil, yalnızca isteğe bağlı günübirlik etkinliktir.' },
      municipality: 'Belediyeye ait karavan servis noktası doğrulanmadı.', marketName: 'Dalyan ikmal seçenekleri', marketNotes: 'Açılış saatini ve Ducato parkını kontrol ederek güncel bir market seçin.', fuelName: 'Yakıt noktası seçilmedi', fuelNotes: 'Sıkışık nehir kıyısı yerine ana yoldaki doğrulanmış bir istasyonu seçin.', waterName: 'İçme suyu dolumu doğrulanmadı', waterNotes: 'Dolumdan önce izinli ve içilebilir bir kaynak ayarlayın.', dumpName: 'Boşaltım noktası doğrulanmadı', dumpNotes: 'Gelmeden lisanslı tesisi teyit edin.', warning1: 'İztuzu korunan kaplumbağa habitatıdır; resmî erişim, ışık ve koruma talimatlarına uyun.', warning2: 'Sazlık, sulak alan veya plaj habitatına araçla girmeyin; Ducato’yu yasal park veya kamp alanında bırakın.', sunrise: 'Kesin seyir önerilmiyor; habitatı rahatsız etmeyen izinli erişimi kullanın.', sunset: 'Yerleşik kasaba nehir kıyısı akşam konusudur; özel mülke ve yaban hayatına saygı gösterin.', photoAlt: 'Dalyan’ın korunan sazlık kanalları'
    },
    karaotBeach: {
      title: 'Karaot Plajı', region: 'Fethiye, Muğla', overview: 'Sulak alanın yanında doğal plaj ve geniş gökyüzü.', whyVisit: 'Kuş gözlemi, şafak yürüyüşü ve sade bir plaj günü için durun.',
      spots: { onur: { title: 'Onur Kamping ve Karavan Alanı', overview: 'Halk plajı parkını kamp alanı saymak yerine Karaot yakınında yasal geceleme üssü olarak seçilen, Yanıklar’daki işletmeli deniz kıyısı karavan kampı.', price: 'Güncel karavan ücretini arayıp 15 m³ Ducato için yer ayırtın.', access: 'Yanıklar ana yaklaşımı ve Deniz Sokak’ı kullanın. Girmeden zemin durumunu ve dönüş alanını teyit edin.' } },
      luna: { subject: 'Sulak alan kuşları ve plaj otları', lens: '70 mm telefoto', timing: 'Gün doğumu', settings: '1/1000 sn, Otomatik ISO, seri çekim', note: 'Yaban hayatını uzaktan fotoğraflayın.' },
      municipality: 'Karaot belediye halk plajı olarak belgelenmiştir; güncel WC, duş, açılış ve karavan hizmetleri doğrulanmadı.', marketName: 'Yakın market seçilmedi', marketNotes: 'Güncel yerel seçenek doğrulanmadıkça ana Fethiye koridorunda ikmali tamamlayın.', fuelName: 'Yakıt noktası seçilmedi', fuelNotes: 'Plaj dönüşünden önce ana yoldaki doğrulanmış bir istasyonu kullanın.', waterName: 'İçme suyu dolumu doğrulanmadı', waterNotes: 'Plaj duşunu içilebilir depo dolum noktası kabul etmeyin.', dumpName: 'Boşaltım noktası doğrulanmadı', dumpNotes: 'Yalnızca karavan atığını kabul eden lisanslı tesisi kullanın.', warning1: 'Özellikle yağmurdan sonra zemin, bariyer ve Ducato dönüş alanını varışta kontrol edin.', warning2: 'Kumul, bitki ve işaretli koruma alanı dışında kalın; gündüz parkı geceleme izni değildir.', sunrise: 'Kesin bir nokta önerilmiyor; habitata girmeden yerleşik umumi erişimi kullanın.', sunset: 'Umumi kıyıyı yalnızca güncel erişim kuralları içinde kullanın ve karanlıktan önce yasal parka dönün.', photoAlt: 'Karaot halk plajı ve açık kıyı peyzajı'
    },
    faralya: {
      title: 'Faralya', region: 'Fethiye, Muğla', overview: 'Kelebekler Vadisi ve Akdeniz üzerinde yüksek dağ köyü.', whyVisit: 'Ducato’yu uygun olmayan uçurum yoluna sokmadan rotanın en büyük uçurumlarını, serin akşamlarını ve gün batımını yaşayın.',
      spots: { aydede: { title: 'Aydede Camping Ölüdeniz', overview: 'Büyük Ducato’yu Faralya uçurum yoluna çıkarmak istemeyenler için Ovacık’taki aşağı kotta işletmeli karavan üssü.', price: 'Sezonluk karavan ücretini ve rezervasyonu yeniden teyit edin.', access: 'Ana Ovacık yaklaşımını kullanın. Yol açıklığı veya trafik uçurum sürüşünü uygun kılmıyorsa Ducato’yu burada bırakıp Faralya–Kabak minibüsüne geçin.', safety: 'Burası güvenli ve temkinli üs seçeneğidir; Faralya’da deniz manzaralı bir yer değildir.' }, bagCamp: { title: 'Bağ Camp Kabak', overview: 'Kabak’ın üstünde panoramik deniz manzarası sunan; campervan yeri, WC, sıcak duş, su, elektrik ve Wi-Fi bulunan küçük işletmeli kamp.', price: 'Alan küçük ve sezonluktur; yola girmeden Ducato uzunluğunu bildirip yer ayırtın.', access: 'Asfalt Faralya–Kabak üst yolundan Kabak Caddesi No. 34’teki işaretli girişe gidin. Karavan yorumları son viraj ve girişi dar olarak tarif ediyor; Kabak sahiline inmeye devam etmeyin.', safety: 'Yalnızca gösterilen alana park edin. Kamp koyun üstündedir; plaja yürüyerek inilir ve dönüş dik tırmanıştır.' } },
      luna: { subject: 'Kelebekler Vadisi ve katmanlı burunlar', lens: '70 mm telefoto', timing: 'Gün batımından önceki kırk dakika', settings: 'RAW, -0,7 EV, odak kilidi', note: 'Korkuluksuz uçurum kenarından çok uzakta durun.' },
      municipality: 'Faralya hizmetleri dağınıktır ve belediyeye ait karavan servis noktası yoktur.', marketName: 'Fethiye veya Ovacık marketleri', marketNotes: 'Ana alışverişi Ölüdeniz’den önce tamamlayın. Faralya ve Kabak’taki küçük sezonluk işletmeler tam karavan ikmali için güvenilir değildir.', fuelName: 'Tırmanıştan önce Ovacık/Fethiye yakıtı', fuelNotes: 'Ölüdeniz’e inip Faralya yoluna başlamadan yakıt alın; uçurum kesiminde istasyon yoktur.', waterName: 'Rezervasyonlu kampta su', waterNotes: 'Bağ Camp misafirler için su listeliyor. Doldurmadan içilebilirliğini sorun; yol kenarı kaynaklarına güvenmeyin.', dumpName: 'Kaset veya gri su boşaltımı doğrulanmadı', dumpNotes: 'Belgelenen kamplar karavan boşaltımı ilan etmiyor; atığı lisanslı tesise kadar tutun.', warning1: 'Ölüdeniz–Faralya asfalt fakat dik, virajlı ve yer yer iki büyük aracın rahat geçemeyeceği kadar dardır. Nisan 2026’da kaya düşmesi yolu kapattı; yamaç riski gerçektir.', warning2: 'Kelebekler Vadisi tabanına araç yolu yoktur. Kabak sahili inişi dik, dar, gevşek zeminli ve keskin virajlıdır: Ducato ile inmeyin.', sunrise: 'Rezervasyonlu üst kamp terasını veya yerleşik köy erişimini kullanın; açık geçiş cebinde durmayın.', sunset: 'Kelebekler Vadisi ve Kabak üstü güçlü gün batımı konularıdır; yerleşik bariyerlerin arkasında ve yol kenarından uzakta kalın.', photoAlt: 'Akdeniz üzerindeki Faralya uçurumları',
      ops: { lastMile: 'Ölüdeniz–Faralya asfalt fakat dar, dik ve uçurumlu; bazı virajlarda iki büyük araç rahat geçemez. Faralya köyü yalnızca dikkatle yönetilebilir. Üst Kabak’a ancak rezervasyonlu bir alan için devam edin; Ducato’yu yukarıda bırakın ve Kabak sahili yoluna kesinlikle inmeyin.', supply: 'Kıyı tırmanışından önce Fethiye veya Ovacık’ta yiyecek ve yakıt alın. Rezervasyonlu kamp su ve WC sağlayabilir; Faralya–Kabak yolunda belgelenmiş boşaltım noktası yoktur.', decision: 'Uçurum yolunda rahat değilseniz Ducato’yu Ovacık’taki Aydede’de bırakıp Faralya–Kabak minibüsünü kullanın. Çıkacaksanız gündüz sürün ve yalnızca Bağ Camp gibi önceden ayarlanmış üst alana gidin. Kelebekler Vadisi tabanına araç yolu yoktur; Kabak sahili inişi Ducato’ya uygun değildir. Açık seyir veya geçiş ceplerinde gecelemeyin.' }
    },
    kas: {
      title: 'Kaş', region: 'Antalya', overview: 'Canlı limanı ve Likya tarihiyle Akdeniz kasabası.', whyVisit: 'Olağanüstü denizi, yemekleri ve Kaputaş kıyı yolunu keşfedin.',
      spots: { kasCamp: { title: 'Kaş Camping', overview: 'Kaş merkezine yaklaşık iki kilometre uzaklıkta, belirlenmiş karavan yerleri ve doğrudan plaj erişimi bulunan işletmeli deniz kıyısı kampı.', price: 'Varıştan önce rezervasyon yapın ve güncel karavan ücretini teyit edin.', access: 'İşaretli Kaş–Kalkan ana yol girişini kullanın. Girmeden 15 m³ Ducato için alan uzunluğunu ve dönüş yerini sorun.' } },
      luna: { subject: 'Liman ışıkları ve Meis', lens: '70 mm telefoto', timing: 'Mavi saat', settings: 'RAW, 1/125 sn, -0,7 EV', note: 'Umumi seyirleri kullanın ve sınır bölgesi kurallarına uyun.' },
      municipality: 'Plaj ve liman ziyaretçi tesisleri karavan servis noktası kabul edilmez.', marketName: 'Kaş ikmal seçenekleri', marketNotes: 'Yasal park ve araç erişimini kontrol ederek güncel bir market seçin.', fuelName: 'Yakıt noktası seçilmedi', fuelNotes: 'Yeterli dönüş alanı olan, doğrulanmış bir D400 istasyonu seçin.', waterName: 'İçme suyu dolumu doğrulanmadı', waterNotes: 'İzinli ve içilebilirliği doğrulanmış bir kaynak ayarlayın.', dumpName: 'Boşaltım noktası doğrulanmadı', dumpNotes: 'Güvenmeden önce lisanslı karavan atık tesisini teyit edin.', warning1: 'Eski şehir, banket ve park uygunluğu uzun Ducato için doğrulanmadı; işaretli ana erişimi kullanın.', warning2: 'Her uçuştan önce güncel drone, korunan alan, deniz ve sınır güvenliği kurallarını kontrol edin.', sunrise: 'Kesin nokta önerilmiyor; erişim saatleri içinde yerleşik liman veya kültür alanı seyri kullanın.', sunset: 'Yasal umumi kıyı seyrini kullanın; korunan alan ve sınır bölgesi talimatlarına uyun.', photoAlt: 'Alacakaranlıkta Kaş limanı ve Akdeniz kıyısı'
    },
    cirali: {
      title: 'Çıralı', region: 'Kemer, Antalya', overview: 'Dağlarla çevrili korunan plajın arkasındaki alçak katlı köy.', whyVisit: 'Yüzün, Olympos’u gezin ve Yanartaş’ın sonsuz alevlerine yürüyün.',
      spots: { olympos222: { title: '222 Camping & Van', overview: '220 V bağlantısı, temiz su noktaları, duş, WC ve ortak kullanım alanları bulunan Çıralı’daki işletmeli karavan alanı.', price: 'Güncel karavan ücretini ve alan durumunu doğrudan teyit edin.', access: 'Çıralı’ya gündüz inin ve işaretli yaklaşımı kullanın. 15 m³ Ducato için kapı ve dönüş ölçülerini varıştan önce sorun.' } },
      luna: { subject: 'Olympos, plaj şafağı ve Yanartaş', lens: '24 mm ana kamera', timing: 'Gün doğumu veya mavi saat', settings: 'Gündüz RAW; Yanartaş’ta Gece modu', note: 'Yuvalama plajında yapay ışık kullanmayın.' },
      municipality: 'Güncel umumi plaj hizmetleri ve karavan servisi doğrulanmadı.', marketName: 'Çıralı ikmal seçenekleri', marketNotes: 'Güncel işletme, saat ve Ducato parkını yerelde teyit edin.', fuelName: 'Yakıt noktası seçilmedi', fuelNotes: 'Ana yol yaklaşımında araç için doğrulanmış bir istasyonda yakıt alın.', waterName: 'İçme suyu dolumu doğrulanmadı', waterNotes: 'Kamp suyu ancak izinle ve içilebilirliği teyit edilerek kullanılmalıdır.', dumpName: 'Boşaltım noktası doğrulanmadı', dumpNotes: 'Herhangi bir tankı boşaltmadan açıkça sorun.', warning1: 'Çıralı ve Olympos korunan habitat ve kaplumbağa yuvalama bağlamındadır; güncel plaj erişimi ve ışık talimatlarına uyun.', warning2: 'Erişim yolu ve bahçe girişleri her Ducato boyu için doğrulanmadı; gündüz inin ve levhaları izleyin.', sunrise: 'Yerleşik umumi plaj, yuvalama ve erişim kurallarına bağlı olarak şafak konusu olabilir.', sunset: 'Olympos tarafında yerleşik erişimi kullanın; açılış koşulları dışında kalıntılara veya habitata girmeyin.', photoAlt: 'Ormanlı dağların altındaki Çıralı Plajı'
    },
    lara: {
      title: 'Lara', region: 'Muratpaşa, Antalya', overview: 'Antalya’nın doğu şehir kıyısında, resmî ziyaretçi hizmetleri bulunan geniş bir halk plajı bölgesi.', whyVisit: 'Rotayı kolay bir şehir-kıyı durağı ve son ikmalle tamamlayın; karavan suyu, atık ve geceleme ihtiyaçlarını ayrıca doğrulayın.',
      luna: { subject: 'Plaj, kumul otları ve Beydağları', lens: '24 mm ana kamera', timing: 'İlk ışık', settings: 'RAW, -0,3 EV, dikeyleri düz tutun', note: 'Çitli kumullara girmeyin ve havalimanı yakınında drone uçurmayın.' },
      municipality: 'Resmî turizm bilgisi soyunma kabini ve yiyecek hizmeti gibi halk plajı olanaklarını belirtir; belediye karavan servisi doğrulanmadı.', marketName: 'Lara şehir ikmali', marketNotes: 'Dar yerel sokaklar yerine yasal Ducato parkı olan güncel bir market seçin.', fuelName: 'Yakıt noktası seçilmedi', fuelNotes: 'Ana şehir yaklaşımında doğrulanmış bir istasyon seçin.', waterName: 'İçme suyu dolumu doğrulanmadı', waterNotes: 'Umumi karavan depo dolum noktası önerilmiyor.', dumpName: 'Boşaltım noktası doğrulanmadı', dumpNotes: 'Aracı depolamadan veya rotayı bitirmeden önce lisanslı boşaltımı doğrulayın.', warning1: 'Güncel şehir, havalimanı yolu ve otel transfer trafiğine pay bırakın; son yaklaşımda canlı navigasyon kullanın.', warning2: 'Yükseklik bariyeri, park kısıtı ve havacılık/drone kurallarını varışta kontrol edin.', sunrise: 'Halk plajı doğal şafak konusudur; erişimi kontrol edip açık ve izinli bir bölüm seçin.', sunset: 'Akşam çekimi için umumi kıyıyı kullanın ve araçtan ayrılmadan park saatlerini doğrulayın.', photoAlt: 'Yumuşak Akdeniz ışığında Lara halk plajı'
    }
  },
  guide: {
    izmir: {
      hiddenTitle: 'Kemeraltı ve tarihî merkez', hiddenDescription: 'Konak Meydanı’ndan Kemeraltı’na yürüyün; zamana ve açılış koşullarına göre Agora veya Tarihî Asansör’ü seçin.',
      beachTitle: 'Plaj değil, şehir kıyısı', beachDescription: 'Kordon yürüyüş, bisiklet ve körfez manzarası içindir. Yüzme için yalnızca resmî olarak belirlenmiş alanları kullanın ve güncel su ile erişim bilgisini kontrol edin.',
      hikingTitle: 'Kordon–Konak şehir yürüyüşü', hikingDescription: 'Kolay bir şehir yürüyüşü için kesintisiz kamusal kıyıyı ve merkezdeki yaya sokaklarını kullanın; bu, doğa parkuru değildir.',
      viewpointTitle: 'Tarihî Asansör terası', viewpointDescription: 'Tarihî Asansörün üst terası İzmir Körfezi’ne bakan yerleşik bir şehir panoramasıdır; gitmeden güncel erişimi kontrol edin.',
      seasonTitle: 'Yıl boyu esnek şehir durağı', seasonDescription: 'Sabit bir mevsim yerine güncel hava durumuna göre plan yapın. Ilık ve kuru koşullar kıyı ve tarihî merkez yürüyüşü için daha uygundur.',
      wcNotes: 'Bu rehber için karavanlara ayrılmış umumi bir tuvalet tesisi doğrulanmadı.', showerNotes: 'Bu rehber için karavanlara ayrılmış belediye duşu doğrulanmadı.', electricityNotes: 'Bu rehber için umumi karavan elektrik bağlantısı doğrulanmadı.',
      practicalTitle: 'Şehir içi sürüş planı', practicalDescription: 'Ana giriş yollarından birinde ikmali tamamlayın, Ducato’yu yasal bir yere park edin ve Konak merkezini yürüyerek veya toplu taşımayla gezin.',
      freecampPrice: 'Önerilen serbest kamp alanı yok', photo1Alt: 'Kordon yürüyüş yolu ve İzmir Körfezi', photo2Alt: 'Mavi saatte İzmir Körfezi’nden geçen vapurlar', photo3Alt: 'Konak’ın tarihî sokakları ve şehir ışıkları'
    },
    guzelcamli: {
      hiddenTitle: 'Yarımada ve delta karşıtlığı', hiddenDescription: 'Korunan alan dağlık yarımadayı delta ve sulak alan habitatlarıyla birleştirir. Geçişi yalnızca izinli yol, patika ve seyirlerden gözlemleyin.',
      beachTitle: 'Dilek Yarımadası koyları', beachDescription: 'İçmeler, Aydınlık, Kavaklıburun ve Karasu parkla ilişkilendirilen yerleşik koy adlarıdır; o gün hangi alanların açık ve erişilebilir olduğunu doğrulayın.',
      hikingTitle: 'Dilek Yarımadası doğa rotaları', hikingDescription: 'Resmî turizm bilgileri yarımadayı doğa yürüyüşü için tanımlar. Yalnızca açık ve işaretli rotaları kullanın; güncel park, yangın ve erişim kısıtlarını önce doğrulayın.',
      viewpointTitle: 'İzinli yarımada seyirleri', viewpointDescription: 'Kıyı ve delta manzaralarını yerleşik yol, patika ve işaretli seyirlerden izleyin; kapalı habitatlara girmeyin ve belirlenmiş erişimin dışına çıkmayın.',
      seasonTitle: 'Yoğun sıcak dışında yürüyüş', seasonDescription: 'İlkbahar ve sonbahar genellikle yürüyüşe, yaz ise yüzmeye daha uygundur ve kalabalık olabilir. Güncel hava ve park kuralları her zaman önceliklidir.',
      wcNotes: 'Rezervasyonlu kampın veya parkın çalışma saatlerindeki belirlenmiş ziyaretçi tuvaletlerini kullanın; her koydaki tesisin açık olduğunu varsaymayın.', showerNotes: 'Hayal Bahçesi misafirleri için sıcak duş listeleniyor. Park plaj hizmetleri karavan servis noktası değildir.', electricityNotes: 'Hayal Bahçesi karavan misafirleri için elektrik listeliyor; yol kenarında umumi karavan bağlantısı yoktur.',
      practicalTitle: 'Yola çıkmadan parkı kontrol edin', practicalDescription: 'Güncel saat ve kısıtlamalar için resmî DKMP kaydını inceleyin, getirdiğiniz her şeyi geri çıkarın ve kısıtlı alanların dışındaki doğrulanmış geceleme noktasına dönün.',
      freecampPrice: 'Önerilen serbest kamp alanı yok', photo1Alt: 'Dilek Yarımadası’nda çamlarla çevrili koy', photo2Alt: 'Güzelçamlı yakınında kayalık Ege kıyısı ve berrak su', photo3Alt: 'Dilek Yarımadası Millî Parkı’nda korunan kıyı habitatı'
    },
    bafaLake: {
      hiddenTitle: 'Athena Tapınağı ve Herakleia taş işçiliği', hiddenDescription: 'Kapıkırı, Herakleia kalıntılarıyla iç içedir. Görülebilen kalıntıları yerleşik köy yollarından gezin; taşlara tırmanmayın, dokunmayın ve hassas alanlara girmeyin.',
      beachTitle: 'Korunan göl kıyısı', beachDescription: 'Bafa’yı klasik bir plaj yerine tabiat parkı göl kıyısı olarak değerlendirin. Yerleşik umumi erişimi kullanın; yüzme ve kıyı kullanımı için yerel yönlendirmeye uyun.',
      hikingTitle: 'Herakleia kültür yürüyüşü', hikingDescription: 'Kapıkırı çevresindeki görülebilen kalıntıları yerleşik köy yollarından gezin. Daha uzun Latmos rotalarında nitelikli yerel rehber kullanın ve hassas kaya resmi alanlarından uzak durun.',
      viewpointTitle: 'Athena Tapınağı peyzajı', viewpointDescription: 'Athena Tapınağı ve köy çevresindeki yerleşik erişim, kalıntılara tırmanmadan göl ve Latmos kaya oluşumları üzerinde geniş manzara sağlar.',
      seasonTitle: 'Ilık yürüyüş havasını seçin', seasonDescription: 'Açık arkeolojik peyzajı ılık ve istikrarlı havada gezmek daha uygundur. Uzun yürüyüşten önce sıcak, rüzgâr ve yağış durumunu kontrol edin.',
      wcNotes: 'Selenes gibi rezervasyonlu bir işletmenin sıhhi tesislerini kullanın; umumi karavan servis noktası önerilmiyor.', showerNotes: 'Duş erişimi işletmeli konaklama veya kampa bağlıdır. Yeri ayırırken teyit edin.', electricityNotes: 'Umumi karavan elektrik bağlantısı önerilmiyor; enerji açısından hazırlıklı gelin ve bağlantıyı doğrudan işletmeyle teyit edin.',
      practicalTitle: 'Hazırlıklı gelin', practicalDescription: 'Köy yoluna dönmeden suyu, büyük alışverişi ve yakıtı tamamlayın. Son yaklaşımı ve yasal park seçeneğini sakin biçimde değerlendirmek için gündüz varın.',
      freecampPrice: 'Önerilen serbest kamp alanı yok', photo1Alt: 'Latmos kaya oluşumları altındaki Bafa Gölü', photo2Alt: 'Kapıkırı köyü içindeki Herakleia taş kalıntıları', photo3Alt: 'Bafa Gölü ve granit kayalarda şafak ışığı'
    },
    faralya: {
      hiddenTitle: 'Kelebekler Vadisi üst seyri', hiddenDescription: 'Korunan vadiyi yalnızca Faralya’daki yerleşik üst erişimden görün. Vadi tabanına araç yolu yoktur; dik patika sıradan bir iniş değildir.',
      beachTitle: 'Kabak Koyu’na yürüyerek', beachDescription: 'Ducato’yu rezervasyonlu üst alanda bırakıp Kabak’a yürüyerek veya uygun yerel transferle inin. Motokaravanı plaj yoluna kesinlikle sokmayın.',
      hikingTitle: 'Faralya–Alınca Likya Yolu', hikingDescription: 'Resmî Likya Yolu etabı Faralya’dan Alınca yönüne devam eder. Rotayı açık bir doğa yürüyüşü olarak ele alın; sıcak, rüzgâr, ayakkabı ve gün ışığını önce kontrol edin.',
      viewpointTitle: 'Üst Faralya kıyı panoraması', viewpointDescription: 'Manzara için yerleşik bir işletme veya işaretli umumi erişim kullanın. Uçurum yolundaki dar geçiş ceplerinde durmayın veya gecelemeyin.',
      practicalTitle: 'Yukarıda park et, hafif keşfet', practicalDescription: 'Gündüz varın, Ducato’yu önceden ayarlanmış üst alana güvenle bırakın ve dik koy inişlerine araçla girmeden kıyıyı keşfedin.'
    }
  },
  spots: {
    izmirFree: { title: 'Doğrulanmış İzmir serbest kampı yok', overview: 'Bu rehber İzmir’de bir şehir içi serbest kamp koordinatı önermiyor. Sahil parkını kamp alanı saymak yerine yasal ve doğrulanmış geceleme tesisi kullanın.', access: 'Gelmeden araç ölçülerini, park levhalarını ve geceleme iznini doğrudan kontrol edin.' },
    izmirPaid: { title: 'İnciraltı Karavan Tesisi', overview: 'Merkeze kolay ulaşılan servisli şehir üssü.', access: 'Rezervasyonda araç uzunluğu sınırını sorun.' },
    guzelcamliFree: { title: 'Doğrulanmış Güzelçamlı serbest kampı yok', overview: 'Kısıtsız bir geceleme noktası önerilmiyor. Yanındaki millî park koruma altındadır; gündüz erişimi kamp izni anlamına gelmez.', access: 'Doğrulanmış kamp veya yasal geceleme alanı kullanın; park ve belediye kurallarını yeniden kontrol edin.' },
    guzelcamliPaid: { title: 'Güzelçamlı Kamp Alanı', overview: 'Dilek Yarımadası gezisi için gölgeli üs.', access: 'Ducato için köy erişimi rahattır.' },
    bafaFree: { title: 'Doğrulanmış Bafa Gölü serbest kampı yok', overview: 'Göl kıyısında serbest kamp koordinatı önerilmiyor. Durak korunan doğal ve arkeolojik peyzaj içindedir.', access: 'İzin veya doğrulanmış tesis ayarlayın; kıyı bitkilerinden ve arkeolojik zeminden uzak durun.' },
    bafaPaid: { title: 'Kapıkırı Pansiyon Kampı', overview: 'Temel köy imkânları sunan küçük işletmeli seçenek.', access: 'Köye girmeden alan ölçülerini teyit edin.' },
    gumuslukFree: { title: 'Gümüşlük İç Bölge Geceleme', overview: 'Sahil yoğunluğundan uzakta iç bölge adayı.', access: 'Özel arazi yaygındır; açık izin alın.' },
    gumuslukPaid: { title: 'Gümüşlük Karavan Kampı', overview: 'Köye yakın servisli üs.', access: 'Sahil kestirmesi yerine ana girişi kullanın.' },
    akyarlarFree: { title: 'Akyarlar İç Bölge Geceleme', overview: 'Düzenlemeli plaj parkından uzakta aday.', access: 'Levhaları kontrol edin, sert rüzgâra hazırlanın.' },
    akyarlarPaid: { title: 'Akyarlar Kıyı Kampı', overview: 'Yüzme koyuna yakın pratik kamp.', access: 'Yükseklik ve uzunluk sınırlarını sorun.' },
    maziFree: { title: 'Mazı Üst Yol Terası', overview: 'Dik plaj yollarının üzerinde uzak aday.', access: 'Orman ve acil geçiş yollarını tamamen açık bırakın.' },
    maziPaid: { title: 'Mazı Aile Kampı', overview: 'Koylara yakın, gölgeli sade kamp.', access: 'Yol ve alan için önceden arayın.' },
    akbukFree: { title: 'Akbük Üst Koy Geceleme', overview: 'Plaj şeridinden uzakta yüksek aday.', access: 'Yalnızca yerleşik ve sağlam cebi kullanın.' },
    akbukPaid: { title: 'Akbük Koyu Kampı', overview: 'Gökova’nın berrak suyu yanında işletmeli seçenek.', access: 'Dik yolu ve dönüş alanını sorun.' },
    dalyanFree: { title: 'Dalyan Kırsal Geceleme', overview: 'Sazlık ve korunan plajdan uzakta kırsal aday.', access: 'Sulama yolları ve yumuşak tarlalardan kaçının.' },
    dalyanPaid: { title: 'Dalyan Bölgesi Kampı', overview: 'Motokaravanı bıraktıktan sonra Dalyan’ı ziyaret etmek için servisli üs.', access: 'Dar nehir merkezinden kaçının.' },
    karaotFree: { title: 'Karaot Plaj Kenarı Geceleme', overview: 'Kumul ve sulak alan dışında sağlam zemin.', access: 'Koruma bariyerlerini asla geçmeyin.' },
    karaotPaid: { title: 'Karaot Ekolojik Kampı', overview: 'Plaja yakın, doğa odaklı işletmeli seçenek.', access: 'Açılış tarihini ve araç kapasitesini teyit edin.' },
    faralyaFree: { title: 'Faralya Üst Köy Geceleme', overview: 'Uçurum kenarlarından uzakta dağ adayı.', access: 'Kıyı yolundaki geçiş ceplerini kapatmayın.' },
    faralyaPaid: { title: 'Faralya Manzara Terası Kampı', overview: 'Güvenli seyirli işletmeli uçurum üstü.', access: 'Ducato ölçülerini önceden bildirin.' },
    kasFree: { title: 'Kaş İç Yayla Geceleme', overview: 'Yoğun kıyıdan uzakta serin aday.', access: 'Yerel izinle yerleşik zemini kullanın.' },
    kasPaid: { title: 'Kaş Yarımada Kampı', overview: 'Deniz erişimli manzaralı servisli üs.', access: 'Yarımada yolu yoğun ve dardır.' },
    ciraliFree: { title: 'Çıralı Üst Köy Geceleme', overview: 'Yuvalama plajından uzakta köy kenarı adayı.', access: 'Yangın kapanışlarına ve özel araziye uyun.' },
    ciraliPaid: { title: 'Çıralı Bahçe Kampı', overview: 'Plaja yakın gölgeli narenciye bahçesi.', access: 'Bazı bahçe girişleri dardır.' },
    laraFree: { title: 'Lara İç Bölge Geceleme', overview: 'Havalimanı hassasiyetinden uzakta kısa şehir adayı.', access: 'Bariyerleri ve park denetimini kontrol edin.' },
    laraPaid: { title: 'Antalya Doğu Karavan Tesisi', overview: 'Yolculuk sonrası için servisli son gece üssü.', access: 'Otel transfer yoğunluğundan kaçının.' }
  }
} satisfies TranslationShape<EnglishContent>

export default content
