type EnglishContent = typeof import('./en').default
type TranslationShape<T> = { [Key in keyof T]: T[Key] extends string ? string : TranslationShape<T[Key]> }

const content = {
  placeholder: {
    routeTitle: 'İzmir - Lara', routeDescription: 'Kişisel karavan rotası.', region: 'Konum bilgileri bekleniyor', overview: 'Konum doğrulandıktan sonra içerik eklenecek.',
    whyVisit: 'Ziyaret notları henüz eklenmedi.', sunrise: 'Gün doğumu konumu eklenmedi.', sunset: 'Gün batımı konumu eklenmedi.'
  },
  route: {
    title: 'Ege’den Akdeniz’e Karavan Rotası',
    description: 'İzmir’den Antalya’ya sakin koylar, antik coğrafyalar ve çamlarla çevrili sahiller boyunca yavaş bir kıyı yolculuğu.'
  },
  facilities: { electricity: 'Elektrik', freshWater: 'Temiz su', wc: 'WC', shower: 'Duş', wasteDisposal: 'Atık boşaltma', restaurant: 'Restoran', wasteBins: 'Yakında çöp kutusu', shade: 'Gölge', supermarkets: 'Yakında süpermarket' },
  prices: { permitted: 'Park izni olan yerlerde ücretsiz', permission: 'Yerel izinle ücretsiz', seasonal: 'Sezonluk ücret; doğrudan teyit edin', reserve: 'Sezonluk ücret; rezervasyon önerilir', premium: 'Yüksek sezon ücreti; önceden ayırtın', local: 'Yerinde sorun; ücretler değişebilir' },
  stops: {
    izmir: {
      title: 'İzmir', region: 'İzmir', overview: 'Kordon kıyısını merkez alan, şehir hizmetlerine ulaşılabilen kentsel rota başlangıcı.', whyVisit: 'Güneye inmeden önce aracı hazırlamak ve Kordon’da yürümek için şehir durağını kullanın. Gece parkı ve servis erişimini yerinde doğrulayın.',
      luna: { subject: 'Kordon vapurları ve sahil yansımaları', lens: '24 mm ana kamera', timing: 'Gün batımından yirmi dakika sonra', settings: 'RAW, -0,7 EV, en az 1/60 sn', note: 'Sahil ışıklarını kullanın; tanınabilir yakın portrelerden kaçının.' },
      municipality: 'Umumi tuvalet ve kutular yaygındır; karavan servisi bulunmaz.', marketName: 'Konak süpermarketleri', marketNotes: 'Büyük marketler ve yerel gıda pazarları.', fuelName: 'Şehir içi akaryakıt istasyonları', fuelNotes: 'D550 güneye çıkmadan depoyu doldurun.', waterName: 'Doğrulanmış halka açık karavan musluğu yok', waterNotes: 'Dolumdan önce kamp veya istasyondan izin alın.', dumpName: 'Doğrulanmış belediye boşaltım noktası yok', dumpNotes: 'Atığı lisanslı bir kampa kadar tutun.', warning1: 'Merkez trafiği işe gidiş saatlerinde yoğundur.', warning2: 'Yükseklik bariyerlerini ve geceleme levhalarını kontrol edin.', sunrise: 'İç körfeze doğuya bakan İnciraltı kıyısı.', sunset: 'Batı ufkundaki vapurlarla Kordon.', photoAlt: 'Sıcak akşam ışığında İzmir sahili'
    },
    guzelcamli: {
      title: 'Güzelçamlı', region: 'Kuşadası, Aydın', overview: 'Kara, deniz ve sulak alan habitatları korunan Dilek Yarımadası–Büyük Menderes Deltası Millî Parkı yanındaki kıyı üssü.', whyVisit: 'Güzelçamlı’yı doğa yürüyüşü ve fotoğraf için üs olarak kullanın. Güncel park saatlerini, araç erişimini ve geceleme kurallarını gelmeden kontrol edin.',
      luna: { subject: 'Çamlarla çevrili koylar ve berrak Ege', lens: '24 mm ana kamera', timing: 'Sabah erken saatler', settings: 'RAW, -0,3 EV, isteğe bağlı polarize filtre', note: 'Belirlenmiş patikalarda kalın ve yaban hayatını koruyun.' },
      municipality: 'Sezonluk kasaba tesisleri millî park kapanışından sonra da hizmet verebilir.', marketName: 'Güzelçamlı merkez marketleri', marketNotes: 'Sebze, ekmek ve temel kamp malzemeleri.', fuelName: 'Davutlar akaryakıt istasyonu', fuelNotes: 'Söke yönüne gitmeden yakıt alın.', waterName: 'Doğrulanmış halka açık içme suyu dolumu yok', waterNotes: 'Ücretli kamptan izin alarak kullanın.', dumpName: 'Halka açık boşaltım noktası yok', dumpNotes: 'Lisanslı kamp servisini kullanın.', warning1: 'Millî park içinde geceleme yalnızca izinli alanlardadır.', warning2: 'Yazın erken dolar; yiyecekleri yaban hayvanlarından koruyun.', sunrise: 'Büyük Menderes deltasına bakan kasaba kıyısı.', sunset: 'Park kapanmadan belirlenmiş Dilek Yarımadası koyu.', photoAlt: 'Çamlarla çevrili turkuaz Ege koyu'
    },
    bafaLake: {
      title: 'Bafa Gölü', region: 'Aydın–Muğla', overview: 'Latmos bölgesi ve Herakleia antik yerleşimiyle ilişkili korunan göl peyzajı.', whyVisit: 'Doğal ve kültürel peyzajı birlikte görmek için durun. Park, erişim ve koruma kurallarını konaklamadan önce yerinde doğrulayın.',
      luna: { subject: 'Latmos yansımaları ve granit kayalar', lens: '24 mm ana kamera', timing: 'Gün doğumundan otuz dakika önce', settings: 'RAW, tripod, ISO 50, pozlama serisi', note: 'Dağlara ölçek vermek için önde bir kaya kullanın.' },
      municipality: 'Kapıkırı’da hizmet sınırlıdır ve karavan tesisi yoktur.', marketName: 'Kapıkırı köy marketi', marketNotes: 'Seçenek az; Söke veya Milas’ta alışveriş yapın.', fuelName: 'D525 üzeri istasyonlar', fuelNotes: 'Ana yoldan ayrılmadan yakıt alın.', waterName: 'Doğrulanmış içme suyu musluğu yok', waterNotes: 'Köye yeterli suyla girin.', dumpName: 'Boşaltım noktası yok', dumpNotes: 'Tüm atığı korunan sulak alandan çıkarın.', warning1: 'Kapıkırı yolu duvarlar ve kayalar arasında daralır.', warning2: 'Yumuşak kıyıya girmeyin; koruma kurallarını teyit edin.', sunrise: 'Önünde Latmos kayalarıyla Kapıkırı kıyısı.', sunset: 'Köyün üzerindeki Herakleia kalıntıları.', photoAlt: 'Şafakta sarp dağların altındaki sakin göl'
    },
    gumusluk: {
      title: 'Gümüşlük', region: 'Bodrum, Muğla', overview: 'Antik Myndos çevresinde, batı manzaralı balıkçı köyü.', whyVisit: 'Taş sokakları, deniz ürünlerini ve Tavşan Adası gün batımını yaşayın.',
      luna: { subject: 'Balıkçı tekneleri ve Tavşan Adası', lens: '70 mm telefoto', timing: 'Gün batımından mavi saate', settings: 'RAW, -0,7 EV, telefonu sabitleyin', note: 'Tekneleri adaya karşı sıkıştırın.' },
      municipality: 'Belediyeye ait karavan servis noktası doğrulanmadı.', marketName: 'Çarşamba yerel pazarı', marketNotes: 'Pazar günü Muğla’nın resmî turizm kaynağında yer alır; güncel konum, saat, araç erişimi ve market seçeneklerini doğrudan doğrulayın.', fuelName: 'Yakıt noktası seçilmedi', fuelNotes: 'Ducato erişimini kontrol ederek ana yarımada yollarındaki bir istasyonu seçin.', waterName: 'İçme suyu dolumu doğrulanmadı', waterNotes: 'Umumi musluğa güvenmeyin; izin alın ve içilebilirliği teyit edin.', dumpName: 'Boşaltım noktası doğrulanmadı', dumpNotes: 'Lisanslı tesis doğrulanana kadar tankları kapalı tutun.', warning1: 'Sahil sokakları ve yasal Ducato parkı sahada doğrulanmadı; gündüz yaklaşın ve levhalara uyun.', warning2: 'Normal park alanı geceleme veya kamp izni sayılmaz.', sunrise: 'Kesin bir gün doğumu noktası doğrulanmadı; gündüz yasal bir umumi seyir bulun.', sunset: 'Batıya bakan umumi sahil akşam konusudur; erişimi ve güvenli parkı varışta doğrulayın.', photoAlt: 'Akşam ışığında Gümüşlük sahili'
    },
    akyarlar: {
      title: 'Akyarlar', region: 'Bodrum, Muğla', overview: 'Sığ denizi ve Kos manzarasıyla güneye bakan koy.', whyVisit: 'Rahat bir yüzme günü geçirin, rüzgâr sörfçülerini fotoğraflayın.',
      luna: { subject: 'Kos silüeti ve rüzgâr sörfçüleri', lens: '70 mm telefoto', timing: 'Öğleden sonra', settings: '1/1000 sn, Otomatik ISO, seri çekim', note: 'Sert rüzgârda telefonu tuzlu sudan koruyun.' },
      municipality: 'Sezonluk plaj hizmetleri ve karavan servis noktası doğrulanmadı.', marketName: 'Perşembe yerel pazarı', marketNotes: 'Pazar günü resmî olarak listelenir; güncel konum, saat ve Ducato parkını yerinde kontrol edin.', fuelName: 'Yakıt noktası seçilmedi', fuelNotes: 'Sonraki kırsal etaptan önce ana yoldaki doğrulanmış bir istasyonda yakıt alın.', waterName: 'İçme suyu dolumu doğrulanmadı', waterNotes: 'Yalnızca izinli ve içilebilirliği teyit edilmiş kaynak kullanın.', dumpName: 'Boşaltım noktası doğrulanmadı', dumpNotes: 'Yalnızca karavan atığını açıkça kabul eden tesisi kullanın.', warning1: 'Plaj park kuralları ve uzun Ducato dönüş alanı seyahat gününde kontrol edilmelidir.', warning2: 'Eski park yorumlarına güvenmek yerine rüzgârı, levhaları ve geceleme kısıtlarını kontrol edin.', sunrise: 'Kesin gün doğumu noktası doğrulanmadı; önce yasal umumi kıyı erişimini inceleyin.', sunset: 'Rüzgâr ve erişim kontrolünden sonra yerleşik umumi kıyıyı kullanın.', photoAlt: 'Akyarlar kıyısı ve açık Ege manzarası'
    },
    mazi: {
      title: 'Mazı', region: 'Bodrum, Muğla', overview: 'Dik dağ yollarıyla ulaşılan çamlarla çevrili uzak koylar.', whyVisit: 'Tatil Bodrum’unun ötesinde berrak su, karanlık gökyüzü ve sessizlik bulun.',
      luna: { subject: 'Çam sırtları, koylar ve Samanyolu', lens: '24 mm ana kamera', timing: 'Mavi saat veya aysız gece', settings: 'Tripodda Gece modu; gündüz RAW', note: 'Sağlam zeminde durun, uzun pozlamada farları kapatın.' },
      municipality: 'Belediyeye ait karavan hizmeti doğrulanmadı.', marketName: 'Cuma yerel pazarı', marketNotes: 'Muğla’nın resmî turizm kaynağı Mazı pazarını cuma günü olarak listeler; konum, ürün ve parkı teyit edin.', fuelName: 'Yakıt noktası seçilmedi', fuelNotes: 'Yeterli yakıtla gelin; belirli bir istasyon önerilmiyor.', waterName: 'İçme suyu dolumu doğrulanmadı', waterNotes: 'Hazırlıklı gelin ve dolumdan önce kaynağı teyit edin.', dumpName: 'Boşaltım noktası doğrulanmadı', dumpNotes: 'Atığı lisanslı servis noktasına taşıyın.', warning1: 'Koy yollarının genişliği, eğimi ve Ducato dönüş alanı sahada doğrulanmadı; seçilen yaklaşımı gündüz inceleyin.', warning2: 'Güncel orman yangını kısıtlarını kontrol edin, orman ve acil geçişi kapatmayın.', sunrise: 'Kesin şafak noktası önerilmiyor; gündüz incelenmiş yerleşik umumi erişimi kullanın.', sunset: 'Sağlam parkı olan, yol ve acil geçişten uzak umumi bir seyir seçin.', photoAlt: 'Ormanlı yamaçlar altındaki Mazı kıyısı'
    },
    akbuk: {
      title: 'Akbük Koyu', region: 'Gökova Körfezi, Muğla', overview: 'Gökova tepeleriyle çevrili berrak sulu geniş koy.', whyVisit: 'İyi yüzme, açık körfez manzarası ve güçlü güneş verimini birleştirin.',
      luna: { subject: 'Gökova su renkleri ve dağ katmanları', lens: '24 mm ana kamera', timing: 'Gün doğumundan sonraki ilk saat', settings: 'RAW, -0,3 EV, isteğe bağlı polarize filtre', note: 'Pus oluşmadan belirlenmiş seyirleri kullanın.' },
      municipality: 'Belediyeye ait karavan servis noktası doğrulanmadı.', marketName: 'Akbük’te ikmal doğrulanmadı', marketNotes: 'Güncel yerel seçenek doğrulanmadıkça büyük alışverişi koya gelmeden tamamlayın.', fuelName: 'Yakıt noktası seçilmedi', fuelNotes: 'Kıyı dönüşünden önce ana yoldaki doğrulanmış bir istasyonda yakıt alın.', waterName: 'İçme suyu dolumu doğrulanmadı', waterNotes: 'Varsa plaj duşlarını içilebilir veya depo dolumuna uygun kabul etmeyin.', dumpName: 'Boşaltım noktası doğrulanmadı', dumpNotes: 'Atığı lisanslı tesise taşıyın.', warning1: 'Son Akbük yaklaşımı her Ducato boyu için sahada doğrulanmadı; güncel rotayı inceleyip gündüz varın.', warning2: 'Yalnızca yasal ve sağlam park kullanın; acil geçişi tamamen açık tutun.', sunrise: 'Kesin bir gün doğumu noktası doğrulanmadı; önce yerleşik kıyı erişimini inceleyin.', sunset: 'Kesin bir seyir önerilmiyor; yasal erişim kullanın ve görüş azalmadan ayrılın.', photoAlt: 'Gökova kıyısındaki Akbük Koyu'
    },
    dalyan: {
      title: 'Dalyan', region: 'Ortaca, Muğla', overview: 'Likya mezarlarına ve korunan sazlıklara bakan nehir kasabası.', whyVisit: 'Kaunos, İztuzu, tekne yolculuğu ve tam karavan ikmalini birleştirin.',
      spots: { sarigerme: { title: 'Sarıgerme Belediye Karavan Alanı', overview: 'Dalyan etabının pratik geceleme üssü olarak seçilen, Sarıgerme kıyısındaki belediye işletmeli çadır ve karavan alanı.', price: 'Güncel sezon ücreti Ortaca Belediyesi ile doğrudan teyit edilmelidir.', access: 'İşaretli Sarıgerme plajı yaklaşımını kullanın. Yola çıkmadan sezon açılışını ve Ducato için yer durumunu teyit edin.' } },
      luna: { subject: 'Dalyan Nehri üzerindeki Likya mezarları', lens: '70 mm telefoto', timing: 'Öğleden sonra', settings: 'RAW, -0,3 EV, teknede 1/250 sn', note: 'Tekneden yavaş geçiş isteyin ve yuvalama alanını koruyun.' },
      municipality: 'Belediyeye ait karavan servis noktası doğrulanmadı.', marketName: 'Dalyan ikmal seçenekleri', marketNotes: 'Açılış saatini ve Ducato parkını kontrol ederek güncel bir market seçin.', fuelName: 'Yakıt noktası seçilmedi', fuelNotes: 'Sıkışık nehir kıyısı yerine ana yoldaki doğrulanmış bir istasyonu seçin.', waterName: 'İçme suyu dolumu doğrulanmadı', waterNotes: 'Dolumdan önce izinli ve içilebilir bir kaynak ayarlayın.', dumpName: 'Boşaltım noktası doğrulanmadı', dumpNotes: 'Gelmeden lisanslı tesisi teyit edin.', warning1: 'İztuzu korunan kaplumbağa habitatıdır; resmî erişim, ışık ve koruma talimatlarına uyun.', warning2: 'Sazlık, sulak alan veya plaj habitatına araçla girmeyin; yasal park ve tekne erişimini yerelde doğrulayın.', sunrise: 'Kesin seyir önerilmiyor; habitatı rahatsız etmeyen izinli erişimi kullanın.', sunset: 'Yerleşik kasaba nehir kıyısı akşam konusudur; tekne trafiğine, özel mülke ve yaban hayatına saygı gösterin.', photoAlt: 'Dalyan’ın korunan sazlık kanalları'
    },
    karaotBeach: {
      title: 'Karaot Plajı', region: 'Fethiye, Muğla', overview: 'Sulak alanın yanında doğal plaj ve geniş gökyüzü.', whyVisit: 'Kuş gözlemi, şafak yürüyüşü ve sade bir plaj günü için durun.',
      luna: { subject: 'Sulak alan kuşları ve plaj otları', lens: '70 mm telefoto', timing: 'Gün doğumu', settings: '1/1000 sn, Otomatik ISO, seri çekim', note: 'Yaban hayatını uzaktan fotoğraflayın.' },
      municipality: 'Karaot belediye halk plajı olarak belgelenmiştir; güncel WC, duş, açılış ve karavan hizmetleri doğrulanmadı.', marketName: 'Yakın market seçilmedi', marketNotes: 'Güncel yerel seçenek doğrulanmadıkça ana Fethiye koridorunda ikmali tamamlayın.', fuelName: 'Yakıt noktası seçilmedi', fuelNotes: 'Plaj dönüşünden önce ana yoldaki doğrulanmış bir istasyonu kullanın.', waterName: 'İçme suyu dolumu doğrulanmadı', waterNotes: 'Plaj duşunu içilebilir depo dolum noktası kabul etmeyin.', dumpName: 'Boşaltım noktası doğrulanmadı', dumpNotes: 'Yalnızca karavan atığını kabul eden lisanslı tesisi kullanın.', warning1: 'Özellikle yağmurdan sonra zemin, bariyer ve Ducato dönüş alanını varışta kontrol edin.', warning2: 'Kumul, bitki ve işaretli koruma alanı dışında kalın; gündüz parkı geceleme izni değildir.', sunrise: 'Kesin bir nokta önerilmiyor; habitata girmeden yerleşik umumi erişimi kullanın.', sunset: 'Umumi kıyıyı yalnızca güncel erişim kuralları içinde kullanın ve karanlıktan önce yasal parka dönün.', photoAlt: 'Karaot halk plajı ve açık kıyı peyzajı'
    },
    faralya: {
      title: 'Faralya', region: 'Fethiye, Muğla', overview: 'Kelebekler Vadisi ve Akdeniz üzerinde yüksek dağ köyü.', whyVisit: 'Rotanın en büyük uçurumlarını, serin akşamlarını ve gün batımını yaşayın.',
      luna: { subject: 'Kelebekler Vadisi ve katmanlı burunlar', lens: '70 mm telefoto', timing: 'Gün batımından önceki kırk dakika', settings: 'RAW, -0,7 EV, odak kilidi', note: 'Korkuluksuz uçurum kenarından çok uzakta durun.' },
      municipality: 'Belediyeye ait karavan servis noktası doğrulanmadı; köy hizmetleri dağınıktır.', marketName: 'Faralya’da ikmal doğrulanmadı', marketNotes: 'Güncel yerel seçenek teyit edilmedikçe dağ etabından önce büyük alışverişi tamamlayın.', fuelName: 'Yakıt noktası seçilmedi', fuelNotes: 'Kıyı tırmanışından önce Ducato erişimi kontrol edilmiş bir istasyonda yakıt alın.', waterName: 'İçme suyu dolumu doğrulanmadı', waterNotes: 'Bir işletmeyle izin ve içilebilirliği teyit etmeden dolum yapmayın.', dumpName: 'Boşaltım noktası doğrulanmadı', dumpNotes: 'Açık tesis onayı olmadan hiçbir tankı boşaltmayın.', warning1: 'Son kıyı yolu ve park geometrisi Ducato için güncel kontrol gerektirir; gündüz varın ve geçiş ceplerini kapatmayın.', warning2: 'Uçurum kenarından uzak durun ve yerleşik araç yollarını terk eden navigasyon önerilerini izlemeyin.', sunrise: 'Kesin umumi gün doğumu konumu doğrulanmadı; yalnızca yasal yerleşik teras kullanın.', sunset: 'Kelebekler Vadisi’ni yerleşik umumi erişimden izleyin ve açık kenarlardan uzak durun.', photoAlt: 'Akdeniz üzerindeki Faralya uçurumları'
    },
    kas: {
      title: 'Kaş', region: 'Antalya', overview: 'Dalış tekneleri ve Likya tarihiyle canlı Akdeniz kasabası.', whyVisit: 'Olağanüstü denizi, yemekleri ve Kaputaş kıyı yolunu keşfedin.',
      luna: { subject: 'Liman tekneleri ve Meis', lens: '70 mm telefoto', timing: 'Mavi saat', settings: 'RAW, 1/125 sn, -0,7 EV', note: 'Umumi seyirleri kullanın ve sınır bölgesi kurallarına uyun.' },
      municipality: 'Plaj ve liman ziyaretçi tesisleri karavan servis noktası kabul edilmez.', marketName: 'Kaş ikmal seçenekleri', marketNotes: 'Yasal park ve araç erişimini kontrol ederek güncel bir market seçin.', fuelName: 'Yakıt noktası seçilmedi', fuelNotes: 'Yeterli dönüş alanı olan, doğrulanmış bir D400 istasyonu seçin.', waterName: 'İçme suyu dolumu doğrulanmadı', waterNotes: 'İzinli ve içilebilirliği doğrulanmış bir kaynak ayarlayın.', dumpName: 'Boşaltım noktası doğrulanmadı', dumpNotes: 'Güvenmeden önce lisanslı karavan atık tesisini teyit edin.', warning1: 'Eski şehir, banket ve park uygunluğu uzun Ducato için doğrulanmadı; işaretli ana erişimi kullanın.', warning2: 'Her uçuştan önce güncel drone, korunan alan, deniz ve sınır güvenliği kurallarını kontrol edin.', sunrise: 'Kesin nokta önerilmiyor; erişim saatleri içinde yerleşik liman veya kültür alanı seyri kullanın.', sunset: 'Yasal umumi kıyı seyrini kullanın; korunan alan ve sınır bölgesi talimatlarına uyun.', photoAlt: 'Alacakaranlıkta Kaş limanı ve Akdeniz kıyısı'
    },
    cirali: {
      title: 'Çıralı', region: 'Kemer, Antalya', overview: 'Dağlarla çevrili korunan plajın arkasındaki alçak katlı köy.', whyVisit: 'Yüzün, Olympos’u gezin ve Yanartaş’ın sonsuz alevlerine yürüyün.',
      luna: { subject: 'Olympos, plaj şafağı ve Yanartaş', lens: '24 mm ana kamera', timing: 'Gün doğumu veya mavi saat', settings: 'Gündüz RAW; Yanartaş’ta Gece modu', note: 'Yuvalama plajında yapay ışık kullanmayın.' },
      municipality: 'Güncel umumi plaj hizmetleri ve karavan servisi doğrulanmadı.', marketName: 'Çıralı ikmal seçenekleri', marketNotes: 'Güncel işletme, saat ve Ducato parkını yerelde teyit edin.', fuelName: 'Yakıt noktası seçilmedi', fuelNotes: 'Ana yol yaklaşımında araç için doğrulanmış bir istasyonda yakıt alın.', waterName: 'İçme suyu dolumu doğrulanmadı', waterNotes: 'Kamp suyu ancak izinle ve içilebilirliği teyit edilerek kullanılmalıdır.', dumpName: 'Boşaltım noktası doğrulanmadı', dumpNotes: 'Herhangi bir tankı boşaltmadan açıkça sorun.', warning1: 'Çıralı ve Olympos korunan habitat ve kaplumbağa yuvalama bağlamındadır; güncel plaj erişimi ve ışık talimatlarına uyun.', warning2: 'Erişim yolu ve bahçe girişleri her Ducato boyu için doğrulanmadı; gündüz inin ve levhaları izleyin.', sunrise: 'Yerleşik umumi plaj, yuvalama ve erişim kurallarına bağlı olarak şafak konusu olabilir.', sunset: 'Olympos tarafında yerleşik erişimi kullanın; açılış koşulları dışında kalıntılara veya habitata girmeyin.', photoAlt: 'Ormanlı dağların altındaki Çıralı Plajı'
    },
    lara: {
      title: 'Lara', region: 'Muratpaşa, Antalya', overview: 'Antalya’nın doğu şehir kıyısında, resmî ziyaretçi hizmetleri bulunan geniş bir halk plajı bölgesi.', whyVisit: 'Rotayı kolay bir şehir-kıyı durağı ve son ikmalle tamamlayın; karavan suyu, atık ve geceleme ihtiyaçlarını ayrıca doğrulayın.',
      luna: { subject: 'Plaj, kumul otları ve Beydağları', lens: '24 mm ana kamera', timing: 'İlk ışık', settings: 'RAW, -0,3 EV, dikeyleri düz tutun', note: 'Çitli kumullara girmeyin ve havalimanı yakınında drone uçurmayın.' },
      municipality: 'Resmî turizm bilgisi soyunma kabini ve yiyecek hizmeti gibi halk plajı olanaklarını belirtir; belediye karavan servisi doğrulanmadı.', marketName: 'Lara şehir ikmali', marketNotes: 'Dar yerel sokaklar yerine yasal Ducato parkı olan güncel bir market seçin.', fuelName: 'Yakıt noktası seçilmedi', fuelNotes: 'Ana şehir yaklaşımında doğrulanmış bir istasyon seçin.', waterName: 'İçme suyu dolumu doğrulanmadı', waterNotes: 'Umumi karavan depo dolum noktası önerilmiyor.', dumpName: 'Boşaltım noktası doğrulanmadı', dumpNotes: 'Aracı depolamadan veya rotayı bitirmeden önce lisanslı boşaltımı doğrulayın.', warning1: 'Güncel şehir, havalimanı yolu ve otel transfer trafiğine pay bırakın; son yaklaşımda canlı navigasyon kullanın.', warning2: 'Yükseklik bariyeri, park kısıtı ve havacılık/drone kurallarını varışta kontrol edin.', sunrise: 'Halk plajı doğal şafak konusudur; erişimi kontrol edip açık ve izinli bir bölüm seçin.', sunset: 'Akşam çekimi için umumi kıyıyı kullanın ve araçtan ayrılmadan park saatlerini doğrulayın.', photoAlt: 'Yumuşak Akdeniz ışığında Lara halk plajı'
    }
  },
  guide: {
    izmir: {
      hiddenTitle: 'Kemeraltı ve tarihî merkez', hiddenDescription: 'Konak Meydanı’ndan Kemeraltı’na yürüyün; zamana ve açılış koşullarına göre Agora veya Tarihî Asansör’ü seçin.',
      beachTitle: 'Plaj değil, şehir kıyısı', beachDescription: 'Kordon yürüyüş, bisiklet ve körfez manzarası içindir. Yüzme için yalnızca resmî olarak belirlenmiş alanları kullanın ve güncel su ile erişim bilgisini kontrol edin.',
      hikingTitle: 'Kordon–Konak şehir yürüyüşü', hikingDescription: 'Kolay bir şehir yürüyüşü için kesintisiz kamusal kıyıyı ve merkezdeki yaya sokaklarını kullanın; bu, doğa parkuru değildir.',
      viewpointTitle: 'Tarihî Asansör terası', viewpointDescription: 'Tarihî Asansörün üst terası İzmir Körfezi’ne bakan yerleşik bir şehir panoramasıdır; gitmeden güncel erişimi kontrol edin.',
      seasonTitle: 'Yıl boyu esnek şehir durağı', seasonDescription: 'Sabit bir mevsim yerine güncel hava durumuna göre plan yapın. Ilık ve kuru koşullar kıyı ve tarihî merkez yürüyüşü için daha uygundur.',
      wcNotes: 'Bu rehber için karavanlara ayrılmış umumi bir tuvalet tesisi doğrulanmadı.', showerNotes: 'Bu rehber için karavanlara ayrılmış belediye duşu doğrulanmadı.', electricityNotes: 'Bu rehber için umumi karavan elektrik bağlantısı doğrulanmadı.',
      practicalTitle: 'Şehir içi sürüş planı', practicalDescription: 'Ana giriş yollarından birinde ikmali tamamlayın, Ducato’yu yasal bir yere park edin ve Konak merkezini yürüyerek veya toplu taşımayla gezin.',
      freecampPrice: 'Önerilen serbest kamp alanı yok', photo1Alt: 'Kordon yürüyüş yolu ve İzmir Körfezi', photo2Alt: 'Mavi saatte İzmir Körfezi’nden geçen vapurlar', photo3Alt: 'Konak’ın tarihî sokakları ve şehir ışıkları'
    },
    guzelcamli: {
      hiddenTitle: 'Yarımada ve delta karşıtlığı', hiddenDescription: 'Korunan alan dağlık yarımadayı delta ve sulak alan habitatlarıyla birleştirir. Geçişi yalnızca izinli yol, patika ve seyirlerden gözlemleyin.',
      beachTitle: 'Dilek Yarımadası koyları', beachDescription: 'İçmeler, Aydınlık, Kavaklıburun ve Karasu parkla ilişkilendirilen yerleşik koy adlarıdır; o gün hangi alanların açık ve erişilebilir olduğunu doğrulayın.',
      hikingTitle: 'Dilek Yarımadası doğa rotaları', hikingDescription: 'Resmî turizm bilgileri yarımadayı doğa yürüyüşü için tanımlar. Yalnızca açık ve işaretli rotaları kullanın; güncel park, yangın ve erişim kısıtlarını önce doğrulayın.',
      viewpointTitle: 'İzinli yarımada seyirleri', viewpointDescription: 'Kıyı ve delta manzaralarını yerleşik yol, patika ve işaretli seyirlerden izleyin; kapalı habitatlara girmeyin ve belirlenmiş erişimin dışına çıkmayın.',
      seasonTitle: 'Yoğun sıcak dışında yürüyüş', seasonDescription: 'İlkbahar ve sonbahar genellikle yürüyüşe, yaz ise yüzmeye daha uygundur ve kalabalık olabilir. Güncel hava ve park kuralları her zaman önceliklidir.',
      wcNotes: 'Kasaba veya park içindeki umumi tuvaletlerin seyahat tarihindeki mevcudiyeti ve sezonluk çalışma durumu doğrulanmadı.', showerNotes: 'Genel karavan kullanımına uygun duş doğrulanmadı; plaj hizmetleri servis noktası kabul edilmemelidir.', electricityNotes: 'Umumi karavan elektrik bağlantısı doğrulanmadı; elektriği yalnızca teyit edilmiş bir kamp üzerinden ayarlayın.',
      practicalTitle: 'Yola çıkmadan parkı kontrol edin', practicalDescription: 'Güncel saat ve kısıtlamalar için resmî DKMP kaydını inceleyin, getirdiğiniz her şeyi geri çıkarın ve kısıtlı alanların dışındaki doğrulanmış geceleme noktasına dönün.',
      freecampPrice: 'Önerilen serbest kamp alanı yok', photo1Alt: 'Dilek Yarımadası’nda çamlarla çevrili koy', photo2Alt: 'Güzelçamlı yakınında kayalık Ege kıyısı ve berrak su', photo3Alt: 'Dilek Yarımadası Millî Parkı’nda korunan kıyı habitatı'
    },
    bafaLake: {
      hiddenTitle: 'Athena Tapınağı ve Herakleia taş işçiliği', hiddenDescription: 'Kapıkırı, Herakleia kalıntılarıyla iç içedir. Görülebilen kalıntıları yerleşik köy yollarından gezin; taşlara tırmanmayın, dokunmayın ve hassas alanlara girmeyin.',
      beachTitle: 'Korunan göl kıyısı', beachDescription: 'Bafa’yı klasik bir plaj yerine tabiat parkı göl kıyısı olarak değerlendirin. Yerleşik umumi erişimi kullanın; yüzme ve kıyı kullanımı için yerel yönlendirmeye uyun.',
      hikingTitle: 'Herakleia kültür yürüyüşü', hikingDescription: 'Kapıkırı çevresindeki görülebilen kalıntıları yerleşik köy yollarından gezin. Daha uzun Latmos rotalarında nitelikli yerel rehber kullanın ve hassas kaya resmi alanlarından uzak durun.',
      viewpointTitle: 'Athena Tapınağı peyzajı', viewpointDescription: 'Athena Tapınağı ve köy çevresindeki yerleşik erişim, kalıntılara tırmanmadan göl ve Latmos kaya oluşumları üzerinde geniş manzara sağlar.',
      seasonTitle: 'Ilık yürüyüş havasını seçin', seasonDescription: 'Açık arkeolojik peyzajı ılık ve istikrarlı havada gezmek daha uygundur. Uzun yürüyüşten önce sıcak, rüzgâr ve yağış durumunu kontrol edin.',
      wcNotes: 'Kapıkırı’da karavan yolcuları için güvenilir bir umumi tuvalet doğrulanmadı.', showerNotes: 'Korunan göl çevresinde umumi karavan duşu doğrulanmadı.', electricityNotes: 'Umumi karavan elektrik bağlantısı doğrulanmadı; enerji açısından hazırlıklı gelin veya teyit edilmiş bir işletme ayarlayın.',
      practicalTitle: 'Hazırlıklı gelin', practicalDescription: 'Köy yoluna dönmeden suyu, büyük alışverişi ve yakıtı tamamlayın. Son yaklaşımı ve yasal park seçeneğini sakin biçimde değerlendirmek için gündüz varın.',
      freecampPrice: 'Önerilen serbest kamp alanı yok', photo1Alt: 'Latmos kaya oluşumları altındaki Bafa Gölü', photo2Alt: 'Kapıkırı köyü içindeki Herakleia taş kalıntıları', photo3Alt: 'Bafa Gölü ve granit kayalarda şafak ışığı'
    }
  },
  spots: {
    izmirFree: { title: 'Doğrulanmış İzmir serbest kampı yok', overview: 'Bu rehber İzmir’de bir şehir içi serbest kamp koordinatı önermiyor. Sahil parkını kamp alanı saymak yerine yasal ve doğrulanmış geceleme tesisi kullanın.', access: 'Gelmeden araç ölçülerini, park levhalarını ve geceleme iznini doğrudan kontrol edin.' },
    izmirPaid: { title: 'İnciraltı Karavan Tesisi', overview: 'Merkeze kolay ulaşılan servisli şehir üssü.', access: 'Rezervasyonda araç uzunluğu sınırını sorun.' },
    guzelcamliFree: { title: 'Doğrulanmış Güzelçamlı serbest kampı yok', overview: 'Kısıtsız bir geceleme noktası önerilmiyor. Yanındaki millî park koruma altındadır; gündüz erişimi kamp izni anlamına gelmez.', access: 'Doğrulanmış kamp veya yasal geceleme alanı kullanın; park ve belediye kurallarını yeniden kontrol edin.' },
    guzelcamliPaid: { title: 'Güzelçamlı Kamp Alanı', overview: 'Dilek Yarımadası gezisi için gölgeli üs.', access: 'Ducato için köy erişimi rahattır.' },
    bafaFree: { title: 'Doğrulanmış Bafa Gölü serbest kampı yok', overview: 'Göl kıyısında serbest kamp koordinatı önerilmiyor. Durak korunan doğal ve arkeolojik peyzaj içindedir.', access: 'İzin veya doğrulanmış tesis ayarlayın; kıyı bitkilerinden ve arkeolojik zeminden uzak durun.' },
    bafaPaid: { title: 'Kapıkırı Pansiyon Kampı', overview: 'Temel köy imkânları sunan küçük işletmeli seçenek.', access: 'Köye girmeden alan ölçülerini teyit edin.' },
    gumuslukFree: { title: 'Gümüşlük İç Bölge Geceleme', overview: 'Sahil yoğunluğundan uzakta iç bölge adayı.', access: 'Özel arazi yaygındır; açık izin alın.' },
    gumuslukPaid: { title: 'Gümüşlük Karavan Kampı', overview: 'Köye yakın servisli üs.', access: 'Sahil kestirmesi yerine ana girişi kullanın.' },
    akyarlarFree: { title: 'Akyarlar İç Bölge Geceleme', overview: 'Düzenlemeli plaj parkından uzakta aday.', access: 'Levhaları kontrol edin, sert rüzgâra hazırlanın.' },
    akyarlarPaid: { title: 'Akyarlar Kıyı Kampı', overview: 'Yüzme koyuna yakın pratik kamp.', access: 'Yükseklik ve uzunluk sınırlarını sorun.' },
    maziFree: { title: 'Mazı Üst Yol Terası', overview: 'Dik plaj yollarının üzerinde uzak aday.', access: 'Orman ve acil geçiş yollarını tamamen açık bırakın.' },
    maziPaid: { title: 'Mazı Aile Kampı', overview: 'Koylara yakın, gölgeli sade kamp.', access: 'Yol ve alan için önceden arayın.' },
    akbukFree: { title: 'Akbük Üst Koy Geceleme', overview: 'Plaj şeridinden uzakta yüksek aday.', access: 'Yalnızca yerleşik ve sağlam cebi kullanın.' },
    akbukPaid: { title: 'Akbük Koyu Kampı', overview: 'Gökova’nın berrak suyu yanında işletmeli seçenek.', access: 'Dik yolu ve dönüş alanını sorun.' },
    dalyanFree: { title: 'Dalyan Kırsal Geceleme', overview: 'Sazlık ve korunan plajdan uzakta kırsal aday.', access: 'Sulama yolları ve yumuşak tarlalardan kaçının.' },
    dalyanPaid: { title: 'Dalyan Nehir Kampı', overview: 'Kaunos ve tekne gezileri için servisli üs.', access: 'Dar nehir merkezinden kaçının.' },
    karaotFree: { title: 'Karaot Plaj Kenarı Geceleme', overview: 'Kumul ve sulak alan dışında sağlam zemin.', access: 'Koruma bariyerlerini asla geçmeyin.' },
    karaotPaid: { title: 'Karaot Ekolojik Kampı', overview: 'Plaja yakın, doğa odaklı işletmeli seçenek.', access: 'Açılış tarihini ve araç kapasitesini teyit edin.' },
    faralyaFree: { title: 'Faralya Üst Köy Geceleme', overview: 'Uçurum kenarlarından uzakta dağ adayı.', access: 'Kıyı yolundaki geçiş ceplerini kapatmayın.' },
    faralyaPaid: { title: 'Faralya Manzara Terası Kampı', overview: 'Güvenli seyirli işletmeli uçurum üstü.', access: 'Ducato ölçülerini önceden bildirin.' },
    kasFree: { title: 'Kaş İç Yayla Geceleme', overview: 'Yoğun kıyıdan uzakta serin aday.', access: 'Yerel izinle yerleşik zemini kullanın.' },
    kasPaid: { title: 'Kaş Yarımada Kampı', overview: 'Deniz erişimli manzaralı servisli üs.', access: 'Yarımada yolu yoğun ve dardır.' },
    ciraliFree: { title: 'Çıralı Üst Köy Geceleme', overview: 'Yuvalama plajından uzakta köy kenarı adayı.', access: 'Yangın kapanışlarına ve özel araziye uyun.' },
    ciraliPaid: { title: 'Çıralı Bahçe Kampı', overview: 'Plaja yakın gölgeli narenciye bahçesi.', access: 'Bazı bahçe girişleri dardır.' },
    laraFree: { title: 'Lara İç Bölge Geceleme', overview: 'Havalimanı hassasiyetinden uzakta kısa şehir adayı.', access: 'Bariyerleri ve park denetimini kontrol edin.' },
    laraPaid: { title: 'Antalya Doğu Karavan Tesisi', overview: 'Yolculuk sonrası için servisli son gece üssü.', access: 'Otel transfer yoğunluğundan kaçının.' }
  }
} satisfies TranslationShape<EnglishContent>

export default content
